#!/usr/bin/env python3
"""Embed the web console (web/) into a C# source file the mod compiles in.

Juno mods ship as a single asset bundle, so shipping loose HTML/CSS/JS next to
the mod would mean an extra install step for the player. Instead the console is
authored as normal web files and baked into WebAssets.g.cs by this script.

Run after editing anything under web/:

    python3 tools/build_web_assets.py
"""

import base64
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
WEB = ROOT / "web"
OUT = ROOT / "unity" / "Assets" / "JunoSecondScreen" / "Scripts" / "Web" / "WebAssets.g.cs"

# route -> (source file, content type, binary?)
ASSETS = [
    ("/", "index.html", "text/html; charset=utf-8", False),
    ("/index.html", "index.html", "text/html; charset=utf-8", False),
    ("/app.css", "app.css", "text/css; charset=utf-8", False),
    ("/app.js", "app.js", "application/javascript; charset=utf-8", False),
    ("/manifest.webmanifest", "manifest.webmanifest", "application/manifest+json; charset=utf-8", False),
    ("/icon.png", "icon.png", "image/png", True),
    ("/favicon.ico", "icon.png", "image/png", True),
]

HEADER = """// <auto-generated>
//     Generated by tools/build_web_assets.py from the files in web/.
//     Do not edit by hand - edit the web sources and re-run the generator.
// </auto-generated>

namespace JunoSecondScreen.Web
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// The tablet console's static files, baked into the mod assembly.
    /// </summary>
    internal static class WebAssets
    {
        private static readonly Dictionary<string, byte[]> Content = new Dictionary<string, byte[]>(StringComparer.Ordinal);
        private static readonly Dictionary<string, string> ContentTypes = new Dictionary<string, string>(StringComparer.Ordinal);
        private static readonly object Gate = new object();
        private static bool _initialized;

        /// <summary>
        /// Looks up a baked asset by request path.
        /// </summary>
        /// <param name="path">The request path, for example <c>/app.js</c>.</param>
        /// <param name="content">The file bytes.</param>
        /// <param name="contentType">The MIME type to serve the file with.</param>
        /// <returns><c>true</c> if the path maps to a baked asset.</returns>
        public static bool TryGet(string path, out byte[] content, out string contentType)
        {
            // Called from connection threads, so the tables are built under a lock.
            lock (Gate)
            {
                Initialize();
                contentType = null;
                return Content.TryGetValue(path, out content) && ContentTypes.TryGetValue(path, out contentType);
            }
        }

        private static void Initialize()
        {
            if (_initialized)
            {
                return;
            }

            _initialized = true;
"""

FOOTER = """        }
    }
}
"""


def csharp_verbatim(text: str) -> str:
    return '@"' + text.replace('"', '""') + '"'


def main() -> int:
    lines = [HEADER]
    for route, filename, content_type, binary in ASSETS:
        source = WEB / filename
        if not source.exists():
            print("missing web asset: {}".format(source), file=sys.stderr)
            return 1

        if binary:
            encoded = base64.b64encode(source.read_bytes()).decode("ascii")
            wrapped = "\" +\n                \"".join(
                encoded[i:i + 100] for i in range(0, len(encoded), 100))
            value = 'Convert.FromBase64String(\n                "{}")'.format(wrapped)
        else:
            text = source.read_text(encoding="utf-8").replace("\r\n", "\n")
            value = "Encoding.UTF8.GetBytes({})".format(csharp_verbatim(text))

        lines.append('            Content["{}"] = {};\n'.format(route, value))
        lines.append('            ContentTypes["{}"] = "{}";\n'.format(route, content_type))
        lines.append("\n")

    lines.append(FOOTER)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(lines), encoding="utf-8")
    total = sum((WEB / name).stat().st_size for _, name, _, _ in ASSETS[1:])
    print("wrote {} ({} bytes of web assets)".format(OUT.relative_to(ROOT), total))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
