// <auto-generated>
//     Generated by tools/build_web_assets.py from the files in web/.
//     Do not edit by hand - edit the web sources and re-run the generator.
// </auto-generated>

namespace JunoSecondScreen.Web
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    /// <summary>
    /// The tablet console's static files, baked into the mod assembly.
    /// </summary>
    internal static class WebAssets
    {
        private static readonly Dictionary<string, byte[]> Content = new Dictionary<string, byte[]>(StringComparer.Ordinal);
        private static readonly Dictionary<string, string> ContentTypes = new Dictionary<string, string>(StringComparer.Ordinal);
        private static readonly object Gate = new object();
        private static bool _initialized;

        /// <summary>
        /// Looks up a baked asset by request path.
        /// </summary>
        /// <param name="path">The request path, for example <c>/app.js</c>.</param>
        /// <param name="content">The file bytes.</param>
        /// <param name="contentType">The MIME type to serve the file with.</param>
        /// <returns><c>true</c> if the path maps to a baked asset.</returns>
        public static bool TryGet(string path, out byte[] content, out string contentType)
        {
            // Called from connection threads, so the tables are built under a lock.
            lock (Gate)
            {
                Initialize();
                contentType = null;
                return Content.TryGetValue(path, out content) && ContentTypes.TryGetValue(path, out contentType);
            }
        }

        private static void Initialize()
        {
            if (_initialized)
            {
                return;
            }

            _initialized = true;
            Content["/"] = Encoding.UTF8.GetBytes(@"<!DOCTYPE html>
<html lang=""en"">
<head>
<meta charset=""utf-8"">
<title>Juno Second Screen</title>
<meta name=""viewport"" content=""width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover"">
<meta name=""apple-mobile-web-app-capable"" content=""yes"">
<meta name=""apple-mobile-web-app-status-bar-style"" content=""black-translucent"">
<meta name=""apple-mobile-web-app-title"" content=""Juno"">
<meta name=""theme-color"" content=""#070b12"">
<link rel=""manifest"" href=""manifest.webmanifest"">
<link rel=""icon"" href=""icon.png"">
<link rel=""apple-touch-icon"" href=""icon.png"">
<link rel=""stylesheet"" href=""app.css"">
</head>
<body>

<header class=""topbar"">
  <div class=""ident"">
    <span id=""craftName"" class=""craft"">—</span>
    <span id=""planetName"" class=""planet"">—</span>
  </div>
  <div class=""clocks"">
    <div class=""clock""><label>MET</label><span id=""met"">T+00:00:00</span></div>
    <div class=""clock""><label>WARP</label><span id=""warp"">1x</span></div>
  </div>
  <nav class=""tabs"" id=""tabs"">
    <button data-tab=""flight"" class=""active"">Flight</button>
    <button data-tab=""orbit"">Orbit</button>
    <button data-tab=""view"">View</button>
  </nav>
  <div class=""link"">
    <span id=""rate"" class=""latency"" title=""Telemetry frames per second"">—</span>
    <span id=""conn"" class=""dot"" title=""Connection""></span>
  </div>
</header>

<main id=""main"">

  <!-- ---------------------------------------------------------------- Flight -->
  <section class=""panel-group"" data-panel=""flight"">
    <div class=""panel navpanel"">
      <canvas id=""navball"" width=""440"" height=""440""></canvas>
      <div class=""attitude"">
        <div class=""pair""><label>PITCH</label><span id=""atPitch"">0°</span></div>
        <div class=""pair""><label>HDG</label><span id=""atHeading"">0°</span></div>
        <div class=""pair""><label>ROLL</label><span id=""atRoll"">0°</span></div>
        <div class=""pair""><label>AoA</label><span id=""atAoa"">0°</span></div>
      </div>
      <div class=""navmodes"">
        <button class=""chip"" data-lock=""prograde"">PRO</button>
        <button class=""chip"" data-lock=""retrograde"">RETRO</button>
        <button class=""chip"" data-lock=""target"">TGT</button>
        <button class=""chip"" data-lock=""node"">NODE</button>
        <button class=""chip"" data-lock=""none"">FREE</button>
      </div>
    </div>

    <div class=""panel readouts"">
      <div class=""bignum"">
        <label>ALTITUDE ASL</label>
        <span id=""altAsl"">—</span>
      </div>
      <div class=""bignum"">
        <label>SURFACE SPEED</label>
        <span id=""surfaceSpeed"">—</span>
      </div>
      <div class=""grid2"">
        <div class=""pair""><label>ALT AGL</label><span id=""altAgl"">—</span></div>
        <div class=""pair""><label>ORBITAL SPD</label><span id=""orbitalSpeed"">—</span></div>
        <div class=""pair""><label>VERT SPD</label><span id=""verticalSpeed"">—</span></div>
        <div class=""pair""><label>HORIZ SPD</label><span id=""horizontalSpeed"">—</span></div>
        <div class=""pair""><label>G-FORCE</label><span id=""gforce"">—</span></div>
        <div class=""pair""><label>MACH</label><span id=""mach"">—</span></div>
        <div class=""pair""><label>APOAPSIS</label><span id=""apoapsisBrief"">—</span></div>
        <div class=""pair""><label>PERIAPSIS</label><span id=""periapsisBrief"">—</span></div>
        <div class=""pair""><label>T&nbsp;TO&nbsp;AP</label><span id=""timeToApBrief"">—</span></div>
        <div class=""pair""><label>T&nbsp;TO&nbsp;PE</label><span id=""timeToPeBrief"">—</span></div>
      </div>
      <div class=""bars"">
        <div class=""bar""><label>FUEL (STAGE)</label><div class=""track""><i id=""barFuel""></i></div><span id=""valFuel"">—</span></div>
        <div class=""bar""><label>MONOPROP</label><div class=""track""><i id=""barMono""></i></div><span id=""valMono"">—</span></div>
        <div class=""bar""><label>BATTERY</label><div class=""track""><i id=""barBatt""></i></div><span id=""valBatt"">—</span></div>
      </div>
    </div>

    <div class=""panel perf"">
      <div class=""grid2"">
        <div class=""pair""><label>TWR</label><span id=""twr"">—</span></div>
        <div class=""pair""><label>&Delta;V STAGE</label><span id=""deltaV"">—</span></div>
        <div class=""pair""><label>THRUST</label><span id=""thrust"">—</span></div>
        <div class=""pair""><label>MASS</label><span id=""mass"">—</span></div>
        <div class=""pair""><label>ISP</label><span id=""isp"">—</span></div>
        <div class=""pair""><label>BURN LEFT</label><span id=""burnTime"">—</span></div>
        <div class=""pair""><label>ENGINES</label><span id=""engines"">—</span></div>
        <div class=""pair""><label>STAGE</label><span id=""stage"">—</span></div>
      </div>
      <div class=""grid2"">
        <div class=""pair""><label>AIR PRESS</label><span id=""airPressure"">—</span></div>
        <div class=""pair""><label>AIR DENS</label><span id=""airDensity"">—</span></div>
        <div class=""pair""><label>LATITUDE</label><span id=""lat"">—</span></div>
        <div class=""pair""><label>LONGITUDE</label><span id=""lon"">—</span></div>
      </div>
    </div>
  </section>

  <!-- ----------------------------------------------------------------- Orbit -->
  <section class=""panel-group"" data-panel=""orbit"" hidden>
    <div class=""panel orbitplot"">
      <canvas id=""orbitCanvas"" width=""620"" height=""620""></canvas>
    </div>
    <div class=""panel readouts"">
      <div class=""bignum""><label>APOAPSIS</label><span id=""apoapsis"">—</span></div>
      <div class=""bignum""><label>PERIAPSIS</label><span id=""periapsis"">—</span></div>
      <div class=""grid2"">
        <div class=""pair""><label>T&nbsp;TO&nbsp;AP</label><span id=""timeToAp"">—</span></div>
        <div class=""pair""><label>T&nbsp;TO&nbsp;PE</label><span id=""timeToPe"">—</span></div>
        <div class=""pair""><label>ECCENTRICITY</label><span id=""ecc"">—</span></div>
        <div class=""pair""><label>INCLINATION</label><span id=""inc"">—</span></div>
        <div class=""pair""><label>PERIOD</label><span id=""period"">—</span></div>
        <div class=""pair""><label>BODY</label><span id=""orbitBody"">—</span></div>
      </div>
    </div>
  </section>

  <!-- ------------------------------------------------------------------ View -->
  <section class=""panel-group"" data-panel=""view"" hidden>
    <div class=""panel viewpanel"">
      <img id=""videoFeed"" alt="""">
      <div class=""viewhint"" id=""viewHint"">Video feed off</div>
      <div class=""viewbar"">
        <button id=""videoToggle"" class=""chip"">Start feed</button>
        <span class=""note"" id=""videoNote""></span>
      </div>
    </div>
  </section>

</main>

<!-- --------------------------------------------------------------- Controls -->
<footer class=""controls"" id=""controls"">
  <div class=""throttle"">
    <label>THROTTLE</label>
    <div class=""tslider"" id=""throttleSlider"">
      <i id=""throttleFill""></i>
      <span id=""throttleValue"">0%</span>
    </div>
  </div>

  <div class=""ctrlmid"">
    <div class=""agrow"" id=""groupRow""></div>
    <div class=""miscrow"">
      <button class=""chip"" data-cmd=""warpDown"">&laquo; WARP</button>
      <button class=""chip"" data-cmd=""warpUp"">WARP &raquo;</button>
      <button class=""chip"" data-cmd=""pause"">PAUSE</button>
      <button class=""chip toggle"" data-cmd=""translation"">RCS TRANSLATE</button>
      <button class=""chip"" data-cmd=""brake"">BRAKE</button>
    </div>
  </div>

  <div class=""stagewrap"">
    <button id=""stageButton"" class=""stage"">STAGE</button>
  </div>
</footer>

<div id=""toast"" class=""toast"" hidden></div>

<script src=""app.js""></script>
</body>
</html>
");
            ContentTypes["/"] = "text/html; charset=utf-8";

            Content["/index.html"] = Encoding.UTF8.GetBytes(@"<!DOCTYPE html>
<html lang=""en"">
<head>
<meta charset=""utf-8"">
<title>Juno Second Screen</title>
<meta name=""viewport"" content=""width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no, viewport-fit=cover"">
<meta name=""apple-mobile-web-app-capable"" content=""yes"">
<meta name=""apple-mobile-web-app-status-bar-style"" content=""black-translucent"">
<meta name=""apple-mobile-web-app-title"" content=""Juno"">
<meta name=""theme-color"" content=""#070b12"">
<link rel=""manifest"" href=""manifest.webmanifest"">
<link rel=""icon"" href=""icon.png"">
<link rel=""apple-touch-icon"" href=""icon.png"">
<link rel=""stylesheet"" href=""app.css"">
</head>
<body>

<header class=""topbar"">
  <div class=""ident"">
    <span id=""craftName"" class=""craft"">—</span>
    <span id=""planetName"" class=""planet"">—</span>
  </div>
  <div class=""clocks"">
    <div class=""clock""><label>MET</label><span id=""met"">T+00:00:00</span></div>
    <div class=""clock""><label>WARP</label><span id=""warp"">1x</span></div>
  </div>
  <nav class=""tabs"" id=""tabs"">
    <button data-tab=""flight"" class=""active"">Flight</button>
    <button data-tab=""orbit"">Orbit</button>
    <button data-tab=""view"">View</button>
  </nav>
  <div class=""link"">
    <span id=""rate"" class=""latency"" title=""Telemetry frames per second"">—</span>
    <span id=""conn"" class=""dot"" title=""Connection""></span>
  </div>
</header>

<main id=""main"">

  <!-- ---------------------------------------------------------------- Flight -->
  <section class=""panel-group"" data-panel=""flight"">
    <div class=""panel navpanel"">
      <canvas id=""navball"" width=""440"" height=""440""></canvas>
      <div class=""attitude"">
        <div class=""pair""><label>PITCH</label><span id=""atPitch"">0°</span></div>
        <div class=""pair""><label>HDG</label><span id=""atHeading"">0°</span></div>
        <div class=""pair""><label>ROLL</label><span id=""atRoll"">0°</span></div>
        <div class=""pair""><label>AoA</label><span id=""atAoa"">0°</span></div>
      </div>
      <div class=""navmodes"">
        <button class=""chip"" data-lock=""prograde"">PRO</button>
        <button class=""chip"" data-lock=""retrograde"">RETRO</button>
        <button class=""chip"" data-lock=""target"">TGT</button>
        <button class=""chip"" data-lock=""node"">NODE</button>
        <button class=""chip"" data-lock=""none"">FREE</button>
      </div>
    </div>

    <div class=""panel readouts"">
      <div class=""bignum"">
        <label>ALTITUDE ASL</label>
        <span id=""altAsl"">—</span>
      </div>
      <div class=""bignum"">
        <label>SURFACE SPEED</label>
        <span id=""surfaceSpeed"">—</span>
      </div>
      <div class=""grid2"">
        <div class=""pair""><label>ALT AGL</label><span id=""altAgl"">—</span></div>
        <div class=""pair""><label>ORBITAL SPD</label><span id=""orbitalSpeed"">—</span></div>
        <div class=""pair""><label>VERT SPD</label><span id=""verticalSpeed"">—</span></div>
        <div class=""pair""><label>HORIZ SPD</label><span id=""horizontalSpeed"">—</span></div>
        <div class=""pair""><label>G-FORCE</label><span id=""gforce"">—</span></div>
        <div class=""pair""><label>MACH</label><span id=""mach"">—</span></div>
        <div class=""pair""><label>APOAPSIS</label><span id=""apoapsisBrief"">—</span></div>
        <div class=""pair""><label>PERIAPSIS</label><span id=""periapsisBrief"">—</span></div>
        <div class=""pair""><label>T&nbsp;TO&nbsp;AP</label><span id=""timeToApBrief"">—</span></div>
        <div class=""pair""><label>T&nbsp;TO&nbsp;PE</label><span id=""timeToPeBrief"">—</span></div>
      </div>
      <div class=""bars"">
        <div class=""bar""><label>FUEL (STAGE)</label><div class=""track""><i id=""barFuel""></i></div><span id=""valFuel"">—</span></div>
        <div class=""bar""><label>MONOPROP</label><div class=""track""><i id=""barMono""></i></div><span id=""valMono"">—</span></div>
        <div class=""bar""><label>BATTERY</label><div class=""track""><i id=""barBatt""></i></div><span id=""valBatt"">—</span></div>
      </div>
    </div>

    <div class=""panel perf"">
      <div class=""grid2"">
        <div class=""pair""><label>TWR</label><span id=""twr"">—</span></div>
        <div class=""pair""><label>&Delta;V STAGE</label><span id=""deltaV"">—</span></div>
        <div class=""pair""><label>THRUST</label><span id=""thrust"">—</span></div>
        <div class=""pair""><label>MASS</label><span id=""mass"">—</span></div>
        <div class=""pair""><label>ISP</label><span id=""isp"">—</span></div>
        <div class=""pair""><label>BURN LEFT</label><span id=""burnTime"">—</span></div>
        <div class=""pair""><label>ENGINES</label><span id=""engines"">—</span></div>
        <div class=""pair""><label>STAGE</label><span id=""stage"">—</span></div>
      </div>
      <div class=""grid2"">
        <div class=""pair""><label>AIR PRESS</label><span id=""airPressure"">—</span></div>
        <div class=""pair""><label>AIR DENS</label><span id=""airDensity"">—</span></div>
        <div class=""pair""><label>LATITUDE</label><span id=""lat"">—</span></div>
        <div class=""pair""><label>LONGITUDE</label><span id=""lon"">—</span></div>
      </div>
    </div>
  </section>

  <!-- ----------------------------------------------------------------- Orbit -->
  <section class=""panel-group"" data-panel=""orbit"" hidden>
    <div class=""panel orbitplot"">
      <canvas id=""orbitCanvas"" width=""620"" height=""620""></canvas>
    </div>
    <div class=""panel readouts"">
      <div class=""bignum""><label>APOAPSIS</label><span id=""apoapsis"">—</span></div>
      <div class=""bignum""><label>PERIAPSIS</label><span id=""periapsis"">—</span></div>
      <div class=""grid2"">
        <div class=""pair""><label>T&nbsp;TO&nbsp;AP</label><span id=""timeToAp"">—</span></div>
        <div class=""pair""><label>T&nbsp;TO&nbsp;PE</label><span id=""timeToPe"">—</span></div>
        <div class=""pair""><label>ECCENTRICITY</label><span id=""ecc"">—</span></div>
        <div class=""pair""><label>INCLINATION</label><span id=""inc"">—</span></div>
        <div class=""pair""><label>PERIOD</label><span id=""period"">—</span></div>
        <div class=""pair""><label>BODY</label><span id=""orbitBody"">—</span></div>
      </div>
    </div>
  </section>

  <!-- ------------------------------------------------------------------ View -->
  <section class=""panel-group"" data-panel=""view"" hidden>
    <div class=""panel viewpanel"">
      <img id=""videoFeed"" alt="""">
      <div class=""viewhint"" id=""viewHint"">Video feed off</div>
      <div class=""viewbar"">
        <button id=""videoToggle"" class=""chip"">Start feed</button>
        <span class=""note"" id=""videoNote""></span>
      </div>
    </div>
  </section>

</main>

<!-- --------------------------------------------------------------- Controls -->
<footer class=""controls"" id=""controls"">
  <div class=""throttle"">
    <label>THROTTLE</label>
    <div class=""tslider"" id=""throttleSlider"">
      <i id=""throttleFill""></i>
      <span id=""throttleValue"">0%</span>
    </div>
  </div>

  <div class=""ctrlmid"">
    <div class=""agrow"" id=""groupRow""></div>
    <div class=""miscrow"">
      <button class=""chip"" data-cmd=""warpDown"">&laquo; WARP</button>
      <button class=""chip"" data-cmd=""warpUp"">WARP &raquo;</button>
      <button class=""chip"" data-cmd=""pause"">PAUSE</button>
      <button class=""chip toggle"" data-cmd=""translation"">RCS TRANSLATE</button>
      <button class=""chip"" data-cmd=""brake"">BRAKE</button>
    </div>
  </div>

  <div class=""stagewrap"">
    <button id=""stageButton"" class=""stage"">STAGE</button>
  </div>
</footer>

<div id=""toast"" class=""toast"" hidden></div>

<script src=""app.js""></script>
</body>
</html>
");
            ContentTypes["/index.html"] = "text/html; charset=utf-8";

            Content["/app.css"] = Encoding.UTF8.GetBytes(@":root {
  --bg: #070b12;
  --panel: #0e141f;
  --panel-2: #131b28;
  --line: #1e2a3d;
  --text: #d8e3f2;
  --muted: #7f90a8;
  --accent: #4fd1e0;
  --accent-dim: #1d6b76;
  --warn: #f0a63c;
  --danger: #e2564d;
  --ok: #57c98a;
  --pad: 10px;
}

* { box-sizing: border-box; -webkit-tap-highlight-color: transparent; }

html, body {
  margin: 0;
  height: 100%;
  overflow: hidden;
  overscroll-behavior: none;
  background: var(--bg);
  color: var(--text);
  font-family: -apple-system, BlinkMacSystemFont, ""SF Pro Text"", ""Segoe UI"", Roboto, sans-serif;
  font-variant-numeric: tabular-nums;
  -webkit-user-select: none;
  user-select: none;
  -webkit-text-size-adjust: 100%;
}

body {
  display: flex;
  flex-direction: column;
  padding: env(safe-area-inset-top) env(safe-area-inset-right) env(safe-area-inset-bottom) env(safe-area-inset-left);
}

/* --------------------------------------------------------------- top bar -- */

.topbar {
  flex: 0 0 auto;
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 8px 14px;
  background: linear-gradient(180deg, #101825, #0a1119);
  border-bottom: 1px solid var(--line);
}

.ident { display: flex; flex-direction: column; min-width: 0; }
.ident .craft { font-size: 16px; font-weight: 600; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.ident .planet { font-size: 11px; color: var(--muted); letter-spacing: .08em; text-transform: uppercase; }

.clocks { display: flex; gap: 14px; }
.clock { display: flex; flex-direction: column; align-items: flex-start; }
.clock label { font-size: 9px; color: var(--muted); letter-spacing: .12em; }
.clock span { font-size: 15px; font-weight: 600; font-variant-numeric: tabular-nums; }

.tabs { margin-left: auto; display: flex; gap: 6px; }
.tabs button {
  appearance: none;
  border: 1px solid var(--line);
  background: var(--panel);
  color: var(--muted);
  padding: 7px 14px;
  border-radius: 8px;
  font-size: 13px;
  font-weight: 600;
}
.tabs button.active { color: #04121a; background: var(--accent); border-color: var(--accent); }

.link { display: flex; align-items: center; gap: 8px; }
.latency { font-size: 11px; color: var(--muted); min-width: 42px; text-align: right; }
.dot { width: 11px; height: 11px; border-radius: 50%; background: var(--danger); box-shadow: 0 0 8px currentColor; }
.dot.live { background: var(--ok); }
.dot.stale { background: var(--warn); }

/* ----------------------------------------------------------------- panels -- */

#main { flex: 1 1 auto; min-height: 0; padding: var(--pad); }

.panel-group {
  display: grid;
  gap: var(--pad);
  height: 100%;
  grid-template-columns: minmax(280px, 1fr) minmax(300px, 1.1fr) minmax(260px, 1fr);
}
.panel-group[data-panel=""orbit""] { grid-template-columns: 1.2fr 1fr; }
.panel-group[data-panel=""view""] { grid-template-columns: 1fr; }
.panel-group[hidden] { display: none; }

.panel {
  background: var(--panel);
  border: 1px solid var(--line);
  border-radius: 12px;
  padding: 12px;
  min-height: 0;
  overflow: hidden;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.bignum { display: flex; flex-direction: column; }
.bignum label { font-size: 10px; color: var(--muted); letter-spacing: .14em; }
.bignum span { font-size: clamp(26px, 4.4vw, 40px); font-weight: 300; line-height: 1.05; letter-spacing: -.01em; }

.grid2 { display: grid; grid-template-columns: 1fr 1fr; gap: 8px 14px; }
.pair { display: flex; flex-direction: column; }
.pair label { font-size: 9px; color: var(--muted); letter-spacing: .12em; }
.pair span { font-size: 17px; font-weight: 500; }

.bars { display: flex; flex-direction: column; gap: 8px; margin-top: auto; }
.bar { display: grid; grid-template-columns: 92px 1fr 52px; align-items: center; gap: 8px; }
.bar label { font-size: 9px; color: var(--muted); letter-spacing: .1em; }
.bar .track { height: 10px; border-radius: 5px; background: var(--panel-2); overflow: hidden; border: 1px solid var(--line); }
.bar .track i { display: block; height: 100%; width: 0; background: var(--accent); transition: width .15s linear; }
.bar span { font-size: 12px; text-align: right; color: var(--muted); }
#barMono { background: var(--warn); }
#barBatt { background: var(--ok); }

/* ---------------------------------------------------------------- navball -- */

.navpanel { align-items: center; }
#navball { width: 100%; max-width: min(100%, 58vh); height: auto; aspect-ratio: 1; }
.attitude { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; width: 100%; }
.attitude .pair span { font-size: 15px; }
.navmodes { display: flex; gap: 6px; flex-wrap: wrap; justify-content: center; }

/* ------------------------------------------------------------- orbit plot -- */

.orbitplot { align-items: center; justify-content: center; }
#orbitCanvas { width: 100%; height: auto; max-height: 100%; aspect-ratio: 1; }

/* ------------------------------------------------------------------ video -- */

.viewpanel { position: relative; align-items: center; justify-content: center; }
#videoFeed { max-width: 100%; max-height: 100%; border-radius: 8px; display: none; }
#videoFeed.on { display: block; }
.viewhint { position: absolute; color: var(--muted); font-size: 14px; }
.viewbar { position: absolute; bottom: 12px; display: flex; align-items: center; gap: 10px; }
.viewbar .note { font-size: 11px; color: var(--muted); }

/* --------------------------------------------------------------- controls -- */

.controls {
  flex: 0 0 auto;
  display: grid;
  grid-template-columns: 150px 1fr 190px;
  gap: var(--pad);
  padding: var(--pad);
  padding-top: 0;
  align-items: stretch;
  height: 172px;
}
.controls.locked { opacity: .45; pointer-events: none; }

.throttle { display: flex; flex-direction: column; gap: 6px; }
.throttle > label { font-size: 9px; color: var(--muted); letter-spacing: .14em; }
.tslider {
  position: relative;
  flex: 1;
  border: 1px solid var(--line);
  border-radius: 12px;
  background: var(--panel);
  overflow: hidden;
  touch-action: none;
}
.tslider i {
  position: absolute;
  left: 0; right: 0; bottom: 0;
  height: 0%;
  background: linear-gradient(180deg, var(--accent), var(--accent-dim));
  transition: height .08s linear;
}
.tslider span {
  position: absolute;
  left: 0; right: 0; top: 50%;
  transform: translateY(-50%);
  text-align: center;
  font-size: 22px;
  font-weight: 600;
  color: var(--text);
  text-shadow: 0 1px 3px rgba(0, 0, 0, .75);
}

.ctrlmid { display: flex; flex-direction: column; gap: var(--pad); min-width: 0; }
.agrow { display: grid; grid-template-columns: repeat(10, 1fr); gap: 6px; flex: 1; }
.miscrow { display: flex; gap: 6px; flex: 0 0 44px; }
.miscrow .chip { flex: 1; }

.ag {
  appearance: none;
  border: 1px solid var(--line);
  background: var(--panel);
  color: var(--muted);
  border-radius: 10px;
  padding: 4px;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: 2px;
  touch-action: manipulation;
  min-width: 0;
}
.ag b { font-size: 19px; font-weight: 600; color: var(--text); }
.ag em { font-style: normal; font-size: 9px; letter-spacing: .04em; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 100%; }
.ag.on { background: var(--accent); border-color: var(--accent); }
.ag.on b, .ag.on em { color: #04121a; }

.chip {
  appearance: none;
  border: 1px solid var(--line);
  background: var(--panel);
  color: var(--text);
  border-radius: 10px;
  padding: 8px 12px;
  font-size: 12px;
  font-weight: 600;
  letter-spacing: .06em;
  touch-action: manipulation;
}
.chip:active { background: var(--panel-2); }
.chip.on { background: var(--accent); border-color: var(--accent); color: #04121a; }

.stagewrap { display: flex; }
.stage {
  appearance: none;
  flex: 1;
  border: 2px solid var(--warn);
  border-radius: 14px;
  background: linear-gradient(180deg, #2a1d08, #1a1206);
  color: var(--warn);
  font-size: 30px;
  font-weight: 700;
  letter-spacing: .18em;
  touch-action: manipulation;
}
.stage:active { background: var(--warn); color: #1a1206; }

/* ------------------------------------------------------------------ toast -- */

.toast {
  position: fixed;
  left: 50%;
  bottom: calc(190px + env(safe-area-inset-bottom));
  transform: translateX(-50%);
  background: #16202f;
  border: 1px solid var(--line);
  color: var(--text);
  padding: 10px 16px;
  border-radius: 10px;
  font-size: 13px;
  z-index: 20;
}

/* ------------------------------------------------------ narrow / portrait -- */

/* Two columns on a portrait tablet, one on a phone. Panels flow and the group
   scrolls rather than squeezing every readout into the fold. */
@media (max-width: 1100px) {
  .panel-group { grid-template-columns: 1fr 1fr; grid-auto-rows: min-content; overflow-y: auto; }
  .panel-group[data-panel=""orbit""] { grid-template-columns: 1fr 1fr; }
  .panel-group[data-panel=""flight""] .perf { grid-column: 1 / -1; }
  .panel-group[data-panel=""flight""] .perf .grid2 { grid-template-columns: repeat(4, 1fr); }
  .clocks { display: none; }
  .controls { grid-template-columns: 120px 1fr 150px; height: 158px; }
  .agrow { grid-template-columns: repeat(5, 1fr); }
  .stage { font-size: 24px; }
}

@media (max-width: 700px) {
  .panel-group,
  .panel-group[data-panel=""orbit""] { grid-template-columns: 1fr; }
  .panel-group[data-panel=""flight""] .perf .grid2 { grid-template-columns: 1fr 1fr; }
  .controls { grid-template-columns: 96px 1fr 120px; height: 150px; }
  .stage { font-size: 20px; }
}
");
            ContentTypes["/app.css"] = "text/css; charset=utf-8";

            Content["/app.js"] = Encoding.UTF8.GetBytes(@"/*
 * Juno Second Screen - tablet console client.
 *
 * Talks to the in-game mod over a single WebSocket: telemetry frames come down,
 * control commands go up. The MJPEG view feed is a separate <img> connection so
 * that video never competes with control latency.
 */
(function () {
  'use strict';

  var TOKEN = new URLSearchParams(location.search).get('t') || '';
  var qs = TOKEN ? '?t=' + encodeURIComponent(TOKEN) : '';

  var el = function (id) { return document.getElementById(id); };
  var state = {
    control: false,
    video: null,
    telemetry: null,
    lastFrameAt: 0,
    groups: [],
    videoOn: false
  };

  /* ------------------------------------------------------------ formatting */

  function fmtDistance(m) {
    if (m === null || m === undefined || !isFinite(m)) return '—';
    var a = Math.abs(m);
    if (a >= 1e9) return (m / 1e9).toFixed(2) + ' Gm';
    if (a >= 1e6) return (m / 1e6).toFixed(2) + ' Mm';
    if (a >= 1e4) return (m / 1e3).toFixed(1) + ' km';
    if (a >= 1e3) return (m / 1e3).toFixed(2) + ' km';
    return m.toFixed(0) + ' m';
  }

  function fmtSpeed(v) {
    if (v === null || v === undefined || !isFinite(v)) return '—';
    if (Math.abs(v) >= 10000) return (v / 1000).toFixed(2) + ' km/s';
    return v.toFixed(Math.abs(v) < 100 ? 1 : 0) + ' m/s';
  }

  function fmtMass(kg) {
    if (!isFinite(kg)) return '—';
    if (kg >= 1000) return (kg / 1000).toFixed(2) + ' t';
    return kg.toFixed(0) + ' kg';
  }

  function fmtClock(seconds) {
    if (!isFinite(seconds) || seconds < 0) return '—';
    if (seconds > 86400 * 999) return '—';
    var s = Math.floor(seconds % 60);
    var m = Math.floor(seconds / 60) % 60;
    var h = Math.floor(seconds / 3600) % 24;
    var d = Math.floor(seconds / 86400);
    var pad = function (n) { return (n < 10 ? '0' : '') + n; };
    return (d > 0 ? d + 'd ' : '') + pad(h) + ':' + pad(m) + ':' + pad(s);
  }

  function fmtDeg(rad, digits) {
    if (!isFinite(rad)) return '—';
    return rad.toFixed(digits === undefined ? 1 : digits) + '°';
  }

  function setText(id, value) {
    var node = el(id);
    if (node && node.textContent !== value) node.textContent = value;
  }

  /* ------------------------------------------------------------- transport */

  var socket = null;
  var retryDelay = 500;
  var frameTimes = [];

  function connect() {
    var scheme = location.protocol === 'https:' ? 'wss:' : 'ws:';
    socket = new WebSocket(scheme + '//' + location.host + '/ws' + qs);

    socket.onopen = function () {
      retryDelay = 500;
      el('conn').className = 'dot live';
    };

    socket.onmessage = function (ev) {
      var msg;
      try { msg = JSON.parse(ev.data); } catch (e) { return; }
      if (msg.type === 'hello') {
        state.control = !!msg.control;
        state.video = msg.video || null;
        applyCapabilities();
      } else if (msg.type === 'telemetry') {
        state.telemetry = msg;
        state.lastFrameAt = performance.now();
        trackFrameRate(state.lastFrameAt);
        render(msg);
      } else if (msg.type === 'toast') {
        toast(msg.text);
      }
    };

    socket.onclose = function () {
      el('conn').className = 'dot';
      frameTimes.length = 0;
      setText('rate', '—');
      setTimeout(connect, retryDelay);
      retryDelay = Math.min(retryDelay * 2, 5000);
    };

    socket.onerror = function () { try { socket.close(); } catch (e) {} };
  }

  function send(obj) {
    if (!socket || socket.readyState !== 1) return;
    socket.send(JSON.stringify(obj));
  }

  // Frames actually arriving per second - a plain, honest link indicator.
  function trackFrameRate(now) {
    frameTimes.push(now);
    while (frameTimes.length > 1 && now - frameTimes[0] > 2000) frameTimes.shift();
    if (frameTimes.length < 2) return;
    var span = (now - frameTimes[0]) / 1000;
    setText('rate', Math.round((frameTimes.length - 1) / span) + ' Hz');
  }

  var toastTimer = null;
  function toast(text) {
    var node = el('toast');
    node.textContent = text;
    node.hidden = false;
    clearTimeout(toastTimer);
    toastTimer = setTimeout(function () { node.hidden = true; }, 2200);
  }

  /* --------------------------------------------------------- capabilities */

  function applyCapabilities() {
    el('controls').classList.toggle('locked', !state.control);
    if (state.video) {
      el('videoNote').textContent = state.video.width + 'px · ' + state.video.fps + ' fps · q' + state.video.quality;
      el('videoToggle').disabled = false;
    } else {
      el('viewHint').textContent = 'Video feed disabled in the mod settings';
      el('videoToggle').disabled = true;
    }
  }

  /* -------------------------------------------------------------- rendering */

  var lastGroupSignature = '';

  function render(t) {
    if (!t.inFlight) {
      setText('craftName', 'Not in flight');
      setText('planetName', '—');
      el('conn').className = 'dot stale';
      return;
    }
    el('conn').className = 'dot live';

    setText('craftName', t.craft || 'Craft');
    setText('planetName', t.planet || '—');
    setText('met', 'T+' + fmtClock(t.met));
    setText('warp', (t.paused ? 'PAUSED' : (t.warp || 1) + 'x'));

    setText('altAsl', fmtDistance(t.altAsl));
    setText('altAgl', fmtDistance(t.altAgl));
    setText('surfaceSpeed', fmtSpeed(t.surfaceSpeed));
    setText('orbitalSpeed', fmtSpeed(t.orbitalSpeed));
    setText('verticalSpeed', fmtSpeed(t.verticalSpeed));
    setText('horizontalSpeed', fmtSpeed(t.horizontalSpeed));
    setText('gforce', isFinite(t.gForce) ? t.gForce.toFixed(2) + ' g' : '—');
    setText('mach', isFinite(t.mach) ? t.mach.toFixed(2) : '—');

    setText('atPitch', fmtDeg(t.pitch));
    setText('atHeading', fmtDeg(t.heading, 0));
    setText('atRoll', fmtDeg(t.roll));
    setText('atAoa', fmtDeg(t.aoa));

    bar('barFuel', 'valFuel', t.fuel);
    bar('barMono', 'valMono', t.monoprop);
    bar('barBatt', 'valBatt', t.battery);

    setText('twr', isFinite(t.twr) ? t.twr.toFixed(2) : '—');
    setText('deltaV', isFinite(t.deltaV) ? Math.round(t.deltaV) + ' m/s' : '—');
    setText('thrust', isFinite(t.thrust) ? (t.thrust / 1000).toFixed(1) + ' kN' : '—');
    setText('mass', fmtMass(t.mass));
    setText('isp', isFinite(t.isp) ? Math.round(t.isp) + ' s' : '—');
    setText('burnTime', fmtClock(t.burnTime));
    setText('engines', (t.activeEngines || 0) + ' / RCS ' + (t.activeRcs || 0));
    setText('stage', (t.stage || 0) + ' / ' + (t.stages || 0));

    setText('airPressure', isFinite(t.airPressure) ? t.airPressure.toFixed(1) + ' Pa' : '—');
    setText('airDensity', isFinite(t.airDensity) ? t.airDensity.toFixed(4) : '—');
    setText('lat', fmtDeg(t.latitude, 3));
    setText('lon', fmtDeg(t.longitude, 3));

    setText('apoapsis', fmtDistance(t.apoapsis));
    setText('periapsis', fmtDistance(t.periapsis));
    setText('timeToAp', fmtClock(t.timeToAp));
    setText('timeToPe', fmtClock(t.timeToPe));
    setText('apoapsisBrief', fmtDistance(t.apoapsis));
    setText('periapsisBrief', fmtDistance(t.periapsis));
    setText('timeToApBrief', fmtClock(t.timeToAp));
    setText('timeToPeBrief', fmtClock(t.timeToPe));
    setText('ecc', isFinite(t.eccentricity) ? t.eccentricity.toFixed(4) : '—');
    setText('inc', fmtDeg(t.inclination, 2));
    setText('period', fmtClock(t.period));
    setText('orbitBody', t.planet || '—');

    if (!throttleHeld) setThrottleDisplay(t.throttle);
    syncGroups(t.groups || []);
    setToggle('translation', t.translationMode);

    drawNavball(t);
    drawOrbit(t);
  }

  function bar(fillId, valueId, fraction) {
    var f = isFinite(fraction) ? Math.max(0, Math.min(1, fraction)) : 0;
    el(fillId).style.width = (f * 100).toFixed(1) + '%';
    setText(valueId, isFinite(fraction) ? Math.round(f * 100) + '%' : '—');
  }

  function setToggle(cmd, on) {
    var node = document.querySelector('[data-cmd=""' + cmd + '""]');
    if (node) node.classList.toggle('on', !!on);
  }

  function syncGroups(groups) {
    var signature = groups.map(function (g) { return g.name; }).join('|');
    var row = el('groupRow');
    if (signature !== lastGroupSignature) {
      lastGroupSignature = signature;
      row.innerHTML = '';
      groups.forEach(function (g) {
        var b = document.createElement('button');
        b.className = 'ag';
        b.dataset.group = g.i;
        b.innerHTML = '<b>' + g.i + '</b><em></em>';
        b.querySelector('em').textContent = g.name || '';
        row.appendChild(b);
      });
    }
    groups.forEach(function (g) {
      var node = row.querySelector('[data-group=""' + g.i + '""]');
      if (node) node.classList.toggle('on', !!g.on);
    });
  }

  /* --------------------------------------------------------------- navball */

  function drawNavball(t) {
    var canvas = el('navball');
    var ctx = canvas.getContext('2d');
    var w = canvas.width, h = canvas.height;
    var cx = w / 2, cy = h / 2, R = Math.min(w, h) / 2 - 14;

    ctx.clearRect(0, 0, w, h);
    ctx.save();
    ctx.beginPath();
    ctx.arc(cx, cy, R, 0, Math.PI * 2);
    ctx.clip();

    var pitch = t.pitch || 0;
    var roll = t.roll || 0;
    var heading = t.heading || 0;
    var pxPerDeg = R / 55;

    ctx.save();
    ctx.translate(cx, cy);
    ctx.rotate(-roll * Math.PI / 180);
    ctx.translate(0, pitch * pxPerDeg);

    ctx.fillStyle = '#1d4f7a';
    ctx.fillRect(-R * 2, -R * 4, R * 4, R * 4);
    ctx.fillStyle = '#6b4a2a';
    ctx.fillRect(-R * 2, 0, R * 4, R * 4);

    ctx.strokeStyle = 'rgba(255,255,255,0.85)';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.moveTo(-R * 2, 0);
    ctx.lineTo(R * 2, 0);
    ctx.stroke();

    ctx.strokeStyle = 'rgba(255,255,255,0.45)';
    ctx.fillStyle = 'rgba(255,255,255,0.7)';
    ctx.lineWidth = 1;
    ctx.font = '11px -apple-system, sans-serif';
    ctx.textAlign = 'center';
    for (var d = -80; d <= 80; d += 10) {
      if (d === 0) continue;
      var y = -d * pxPerDeg;
      var half = (d % 30 === 0) ? R * 0.32 : R * 0.16;
      ctx.beginPath();
      ctx.moveTo(-half, y);
      ctx.lineTo(half, y);
      ctx.stroke();
      if (d % 30 === 0) ctx.fillText(String(d), half + 16, y + 4);
    }
    ctx.restore();

    // Heading tape, kept well inside the rim so the circular clip cannot cut it.
    var tapeY = cy - R * 0.80;
    ctx.fillStyle = 'rgba(7,11,18,0.55)';
    ctx.fillRect(cx - R * 0.55, tapeY - 12, R * 1.10, 26);
    ctx.strokeStyle = 'rgba(216,227,242,0.55)';
    ctx.fillStyle = 'rgba(216,227,242,0.9)';
    ctx.font = '12px -apple-system, sans-serif';
    ctx.textAlign = 'center';
    for (var hd = 0; hd < 360; hd += 30) {
      var rel = ((hd - heading + 540) % 360) - 180;
      if (Math.abs(rel) > 60) continue;
      var x = cx + (rel / 60) * R * 0.50;
      ctx.beginPath();
      ctx.moveTo(x, tapeY - 10);
      ctx.lineTo(x, tapeY - 4);
      ctx.stroke();
      ctx.fillText(hd === 0 ? 'N' : hd === 90 ? 'E' : hd === 180 ? 'S' : hd === 270 ? 'W' : String(hd), x, tapeY + 8);
    }

    ctx.strokeStyle = '#4fd1e0';
    ctx.beginPath();
    ctx.moveTo(cx, tapeY - 14);
    ctx.lineTo(cx - 4, tapeY - 20);
    ctx.lineTo(cx + 4, tapeY - 20);
    ctx.closePath();
    ctx.stroke();

    drawMarker(ctx, cx, cy, R, t.cf, t.cr, t.cu, t.prograde, '#57c98a', 'pro');
    drawMarker(ctx, cx, cy, R, t.cf, t.cr, t.cu, negate(t.prograde), '#e2564d', 'retro');
    if (t.targetDir) drawMarker(ctx, cx, cy, R, t.cf, t.cr, t.cu, t.targetDir, '#f0a63c', 'target');

    ctx.restore();

    // fixed craft reticle
    ctx.strokeStyle = '#4fd1e0';
    ctx.lineWidth = 2.5;
    ctx.beginPath();
    ctx.moveTo(cx - R * 0.30, cy); ctx.lineTo(cx - R * 0.08, cy);
    ctx.moveTo(cx + R * 0.08, cy); ctx.lineTo(cx + R * 0.30, cy);
    ctx.moveTo(cx, cy - R * 0.10); ctx.lineTo(cx, cy - R * 0.02);
    ctx.stroke();

    ctx.strokeStyle = 'rgba(216,227,242,0.35)';
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(cx, cy, R, 0, Math.PI * 2);
    ctx.stroke();
  }

  function negate(v) { return v ? [-v[0], -v[1], -v[2]] : null; }

  function drawMarker(ctx, cx, cy, R, fwd, right, up, dir, color, kind) {
    if (!fwd || !right || !up || !dir) return;
    var df = dot(dir, fwd), dr = dot(dir, right), du = dot(dir, up);
    var x = cx + dr * R;
    var y = cy - du * R;
    var behind = df < 0;

    ctx.save();
    ctx.globalAlpha = behind ? 0.3 : 1;
    ctx.strokeStyle = color;
    ctx.lineWidth = 2.5;
    ctx.beginPath();
    ctx.arc(x, y, R * 0.075, 0, Math.PI * 2);
    ctx.stroke();

    ctx.beginPath();
    if (kind === 'retro') {
      var s = R * 0.075;
      ctx.moveTo(x - s, y - s); ctx.lineTo(x + s, y + s);
      ctx.moveTo(x + s, y - s); ctx.lineTo(x - s, y + s);
    } else if (kind === 'target') {
      ctx.moveTo(x - R * 0.13, y); ctx.lineTo(x + R * 0.13, y);
      ctx.moveTo(x, y - R * 0.13); ctx.lineTo(x, y + R * 0.13);
    } else {
      ctx.moveTo(x - R * 0.15, y); ctx.lineTo(x - R * 0.075, y);
      ctx.moveTo(x + R * 0.075, y); ctx.lineTo(x + R * 0.15, y);
      ctx.moveTo(x, y - R * 0.15); ctx.lineTo(x, y - R * 0.075);
      ctx.arc(x, y, R * 0.02, 0, Math.PI * 2);
    }
    ctx.stroke();
    ctx.restore();
  }

  function dot(a, b) { return a[0] * b[0] + a[1] * b[1] + a[2] * b[2]; }

  /* ----------------------------------------------------------- orbit plot */

  function drawOrbit(t) {
    var canvas = el('orbitCanvas');
    var ctx = canvas.getContext('2d');
    var w = canvas.width, h = canvas.height;
    ctx.clearRect(0, 0, w, h);

    var Rp = t.planetRadius;
    if (!isFinite(Rp) || Rp <= 0) return;

    var rp = t.periapsis + Rp;
    var ra = t.apoapsis + Rp;
    var suborbital = !(isFinite(ra) && ra > rp && rp > 0);
    var a = (ra + rp) / 2;
    var e = suborbital ? (isFinite(t.eccentricity) ? t.eccentricity : 0) : (ra - rp) / (ra + rp);

    var extent = suborbital ? Rp * 1.6 : Math.max(ra, Rp * 1.2) * 1.12;
    var scale = (Math.min(w, h) / 2 - 12) / extent;
    var cx = w / 2, cy = h / 2;

    // planet
    var grd = ctx.createRadialGradient(cx, cy, Rp * scale * 0.2, cx, cy, Rp * scale);
    grd.addColorStop(0, '#1b3b57');
    grd.addColorStop(1, '#0e2233');
    ctx.fillStyle = grd;
    ctx.beginPath();
    ctx.arc(cx, cy, Rp * scale, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = '#2b5877';
    ctx.lineWidth = 1;
    ctx.stroke();

    if (isFinite(t.atmosphereHeight) && t.atmosphereHeight > 0) {
      ctx.save();
      ctx.setLineDash([4, 6]);
      ctx.strokeStyle = 'rgba(79,209,224,0.35)';
      ctx.beginPath();
      ctx.arc(cx, cy, (Rp + t.atmosphereHeight) * scale, 0, Math.PI * 2);
      ctx.stroke();
      ctx.restore();
    }

    if (!suborbital) {
      var b = a * Math.sqrt(Math.max(0, 1 - e * e));
      var c = a * e;
      ctx.save();
      ctx.translate(cx - c * scale, cy);
      ctx.strokeStyle = '#4fd1e0';
      ctx.lineWidth = 1.8;
      ctx.beginPath();
      ctx.ellipse(0, 0, a * scale, b * scale, 0, 0, Math.PI * 2);
      ctx.stroke();
      ctx.restore();

      marker(ctx, cx + ra * scale, cy, '#f0a63c', 'Ap');
      marker(ctx, cx - rp * scale, cy, '#57c98a', 'Pe');

      // craft position from the conic equation, branch chosen by radial velocity
      var r = t.radius;
      if (isFinite(r) && r > 0 && e >= 0) {
        var cosNu = e > 1e-6 ? ((a * (1 - e * e) / r) - 1) / e : 1;
        cosNu = Math.max(-1, Math.min(1, cosNu));
        var nu = Math.acos(cosNu);
        if (t.verticalSpeed < 0) nu = -nu;
        var px = cx + r * Math.cos(nu) * scale;
        var py = cy - r * Math.sin(nu) * scale;
        ctx.fillStyle = '#ffffff';
        ctx.beginPath();
        ctx.arc(px, py, 5, 0, Math.PI * 2);
        ctx.fill();
      }
    } else {
      ctx.fillStyle = '#7f90a8';
      ctx.font = '14px -apple-system, sans-serif';
      ctx.textAlign = 'center';
      ctx.fillText('Suborbital', cx, cy + Rp * scale + 26);
    }

    ctx.textAlign = 'left';
  }

  function marker(ctx, x, y, color, label) {
    ctx.fillStyle = color;
    ctx.beginPath();
    ctx.arc(x, y, 4, 0, Math.PI * 2);
    ctx.fill();
    ctx.font = '12px -apple-system, sans-serif';
    ctx.fillText(label, x + 8, y + 4);
  }

  /* ---------------------------------------------------------------- input */

  var throttleHeld = false;

  function setThrottleDisplay(v) {
    var f = Math.max(0, Math.min(1, isFinite(v) ? v : 0));
    el('throttleFill').style.height = (f * 100).toFixed(1) + '%';
    setText('throttleValue', Math.round(f * 100) + '%');
  }

  function bindThrottle() {
    var slider = el('throttleSlider');
    var lastSent = 0;

    function valueFromEvent(ev) {
      var rect = slider.getBoundingClientRect();
      return Math.max(0, Math.min(1, 1 - (ev.clientY - rect.top) / rect.height));
    }

    function push(ev) {
      var v = valueFromEvent(ev);
      setThrottleDisplay(v);
      var now = performance.now();
      if (now - lastSent > 45) {
        lastSent = now;
        send({ cmd: 'throttle', v: v });
      }
      return v;
    }

    slider.addEventListener('pointerdown', function (ev) {
      throttleHeld = true;
      slider.setPointerCapture(ev.pointerId);
      push(ev);
      ev.preventDefault();
    });
    slider.addEventListener('pointermove', function (ev) {
      if (throttleHeld) push(ev);
    });
    function release(ev) {
      if (!throttleHeld) return;
      throttleHeld = false;
      send({ cmd: 'throttle', v: valueFromEvent(ev) });
    }
    slider.addEventListener('pointerup', release);
    slider.addEventListener('pointercancel', release);
  }

  function bindButtons() {
    el('stageButton').addEventListener('pointerdown', function (ev) {
      ev.preventDefault();
      send({ cmd: 'stage' });
      if (navigator.vibrate) navigator.vibrate(15);
    });

    el('groupRow').addEventListener('pointerdown', function (ev) {
      var button = ev.target.closest('.ag');
      if (!button) return;
      ev.preventDefault();
      var on = !button.classList.contains('on');
      button.classList.toggle('on', on);
      send({ cmd: 'ag', i: Number(button.dataset.group), on: on });
    });

    document.querySelectorAll('[data-cmd]').forEach(function (button) {
      var cmd = button.dataset.cmd;
      if (cmd === 'brake') {
        button.addEventListener('pointerdown', function (ev) { ev.preventDefault(); send({ cmd: 'brake', v: 1 }); });
        button.addEventListener('pointerup', function () { send({ cmd: 'brake', v: 0 }); });
        button.addEventListener('pointercancel', function () { send({ cmd: 'brake', v: 0 }); });
        return;
      }
      button.addEventListener('pointerdown', function (ev) {
        ev.preventDefault();
        if (cmd === 'warpUp') send({ cmd: 'warp', d: 1 });
        else if (cmd === 'warpDown') send({ cmd: 'warp', d: -1 });
        else if (cmd === 'pause') send({ cmd: 'pause' });
        else if (cmd === 'translation') send({ cmd: 'translation' });
      });
    });

    document.querySelectorAll('[data-lock]').forEach(function (button) {
      button.addEventListener('pointerdown', function (ev) {
        ev.preventDefault();
        send({ cmd: 'lock', mode: button.dataset.lock });
      });
    });
  }

  function bindTabs() {
    el('tabs').addEventListener('click', function (ev) {
      var button = ev.target.closest('button');
      if (!button) return;
      document.querySelectorAll('#tabs button').forEach(function (b) { b.classList.toggle('active', b === button); });
      document.querySelectorAll('.panel-group').forEach(function (panel) {
        panel.hidden = panel.dataset.panel !== button.dataset.tab;
      });
    });
  }

  function bindVideo() {
    var img = el('videoFeed');
    el('videoToggle').addEventListener('click', function () {
      state.videoOn = !state.videoOn;
      if (state.videoOn) {
        img.src = '/stream.mjpg' + qs + (qs ? '&' : '?') + 'r=' + Date.now();
        img.classList.add('on');
        el('viewHint').hidden = true;
        el('videoToggle').textContent = 'Stop feed';
      } else {
        img.removeAttribute('src');
        img.classList.remove('on');
        el('viewHint').hidden = false;
        el('viewHint').textContent = 'Video feed off';
        el('videoToggle').textContent = 'Start feed';
      }
    });
    img.addEventListener('error', function () {
      if (state.videoOn) el('videoNote').textContent = 'feed interrupted';
    });
  }

  /* --------------------------------------------------------------- staleness */

  setInterval(function () {
    if (!state.lastFrameAt) return;
    if (performance.now() - state.lastFrameAt > 2000 && socket && socket.readyState === 1) {
      el('conn').className = 'dot stale';
    }
  }, 1000);

  document.addEventListener('gesturestart', function (ev) { ev.preventDefault(); });
  document.addEventListener('dblclick', function (ev) { ev.preventDefault(); });

  bindThrottle();
  bindButtons();
  bindTabs();
  bindVideo();
  connect();
})();
");
            ContentTypes["/app.js"] = "application/javascript; charset=utf-8";

            Content["/manifest.webmanifest"] = Encoding.UTF8.GetBytes(@"{
  ""name"": ""Juno Second Screen"",
  ""short_name"": ""Juno"",
  ""start_url"": ""./"",
  ""display"": ""standalone"",
  ""orientation"": ""landscape"",
  ""background_color"": ""#070b12"",
  ""theme_color"": ""#070b12"",
  ""icons"": [
    { ""src"": ""icon.png"", ""sizes"": ""180x180"", ""type"": ""image/png"" }
  ]
}
");
            ContentTypes["/manifest.webmanifest"] = "application/manifest+json; charset=utf-8";

            Content["/icon.png"] = Convert.FromBase64String(
                "iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAIAAACyr5FlAAAk30lEQVR42u2d+XNUVdrH+7cZMAtk30nIQshOtoasJjGkgyFDcAER" +
                "GRGFYhWYCdsADg5gEKZAClnGMEwBQjGAhEEQZIksMiDIomWhVo3zw/sPvPX+Be/nptMm3X2Xc27fTkK4VeeHLPeec57v8+nnec65" +
                "Szt+81yE3eym2hy2BHaz4bCbDYfJFunXbE2eITgiLW02HDYKzzYujmcIiBCL2jMDimPYMqHp3agAmiwuNhxDhwmLUTCFyzCixDHs" +
                "mDD26G9NNWlWnn5KHE8xFgJMiDk+WqMFQow+JTYcQcLCiAkJAkIFmjA38pTYcAQlVIgAIQmBbNNlRY+SpyeQOJ4CMrRDhSYQoQPe" +
                "NEARDiQ2HOax0A8VUkzEBNBMUiIcSGw4AsBChQkTKITFjoxOCU3MCE/NGZVRMDq7OCKnNDKvPDLfqbS8cn7lj/yLAziMgznFDC7G" +
                "lAxpRBxDuOTUwsIwTnj5b0REYlhKdkROSUxpTXyNK7mpbUzrrLGvzs2YvSBr7tLs+SvGL2zPWbImd9na3GXretpafuWP/IsDOIyD" +
                "OYUTOZ1O6IoO6VYUFL9Yoo7I0CtEHEMyYOhiIcBESFwaH/1YZ11S47S06W9kzlk0ftGq/PZNEzZuL+3Y49zVWbHvaNXBf9Yc7qo9" +
                "fr7u5MX605frz1xt6LpG4wd+5Y/8iwM4jIM5hRM5nU7oig7pls4ZgoEYToYScUSeaTgM8ogYFp4IER4Xnp4XU1bLRzx9xrzsBX8o" +
                "WPWXki0fTdx9qOrQKZzdeP6mq/vBi3eetD76b8vdH6fc/M517f7kS/9uvHDrhXPXG852u+HgB37lj/yLAziMgzmFEzmdTuiKDumW" +
                "zhmCgRiOQRmaCTANA0r0EBlaWcYxNAOGABa/FhBxFAdxk14Y0/oaWSD/j38u2bqbzzqfexw85evvWx/+0nzjceOFr+tOXao5fKZi" +
                "/zHnroNl2/YWv7+zaMO2wjVbCto35a/cmLd8fd67f1La8vX8yh/5FwdwGAdzCidyOp3QFR3SLZ0zBAMxHIMyNBNgGkyGKTExPUoM" +
                "ERkCfDieXizCksfxYU1pmZH11rKC1ZvLdxyo/sdpPvT4bOq9n5su38WRJAXnzk4czEc8Z/HqcXOXps+clzrt9RTXS4n1LfFVTXHO" +
                "esqI6AmV0YWTogom0viBX/kj/+IADuNgTuFETqcTuqJDuqVzhmAghmNQhmYCTIPJMCUmxvSY5NOLiGNIkqGLRVgsaT6xriVj1jt5" +
                "KzfyscYlRPuWb34iBZAXqv5+svyvB4rWd+QuWZM5ZyF+TWqYSnEQmVs2Ki03JG7siPD4EWFxci08nhM5nU6UUqZhKt3SOUMwEMMx" +
                "KEMrOeibn5gMU2JiTI9JMlUm3G+9o4fIkOLDMThk+FUYXgFDAwsWCHyyk5tfHvf2u0UbPySYUzy+ePuHKbe+r//sSuWB4yVbdpMR" +
                "sn6/OLX1tYRqV1S+U1lWjEqQRkGkjUqgc4ZgIIZjUIZmAkyDyTAlJsb0mCRTZcJMm8n3W+OoIuIfQvyrkOEJh7mA4cGiqGLM1Jms" +
                "MCkD+VxO/vJO64P/kPL5yJZ+sCdvxYbM2QuSm6aTDvh8q8eGcIuaWlxhUIZmAkyDyTAlJsb0mCRTZcJMm8ljAoZoIiIaQoYVHJqp" +
                "RDdg9CaRyHwn+ZsFJIvJmqP/av7qIR9Kkj3rhcK1W6kDUqa8gmOUICENRLxAkwOFaTAZpsTEmB6TZKpMmGkzeUzAEMzBKM1EoxNC" +
                "BjbFOIYAGZoBY3RWEUvE7PkrWQsoWNx4xDKh9tjnZdv3s6ZIf3UuIX10ZoEYEPGWNmNQmBjTY5JMlQkzbSaPCRiCORiFaRgoE0IG" +
                "mg/H4KcSNSxCEzPiq5sy5yya8N4OYrKr+wG1Xu2n50o7Pma9QDEYW1YbmpBpxET8gDQ9SpgkU2XCTJvJY4Kyv9L9AKMwDQMxE2P1" +
                "Q8hgpRjHwJOhnUp6l3xRhZPSpr+R376Jam7yxdstd588f+KLsg/3KVi0vsY687noMbpYGHt0pGQzQ0m/GTJhps3kMQFDMAejMA0D" +
                "MRNjMVl9xSuUYp4+OGRTSU/ASMpi4Zc9fwXrwLpTX1LNNZztdu46SGROa5sdU1z1XFSKCSa8PZ3Q20YJt19PEcVFnRImjwkYgjkY" +
                "hWkYiJkYi8kYjvkafEQPCh+OoUNGZF45n6GC1ZsrO09Qvrmu3a/85AQ1XfrMeXHOemV/Qh0LQyAkUZDAxRAUFUQwBHMwCtMwEDMx" +
                "FpMxHPMRYejw4RgEMvywGBmZFFfRmDV3KcV8/enLrQ9/qTt5kdVg9tvLE+tbwlNzxLHwYmLUgDRjSlQQwShMw0DMxFhMxnDMRwSk" +
                "QBCdFDNgfDgGnQzWftTtucvWTdp7pOnKPVf3t5UHjheQidtmR+U75bGQcm2iQJOmRBwRDMRMjMVkDMd8REAKBEGWQefDMbhkjM4u" +
                "Tm2bXbhua83hrpZvfmrouka9xucpobbZazGijYUwE4mWNtOU+PKBmRiLyRiO+YiAFAiCLMqm+6Dy4RhEMqKKKjJmvVOyeRcRdeq9" +
                "n2uOnC1a3zH2lTejCydZh0VikJs1iGAyhmM+IiAFgiAL4iDRIPJhNRzCZMSUP09+Ld9xoPHCrebrjyr2H6OGT3G9pGx+G5FhhIWR" +
                "R0ebauZA0UTElw8Mx3xEQAoEQRbEQSKEkudjaMHRP2wYkREWS82VPX/lxN2HXFeV222cOzv5NaHa1beBYS0WXm5O0mo//s//0XQO" +
                "EGPFPCKYjwhIgSDKrUZX7yMRvyKXZ6/diA9Lg4djgMlAiPjqpvGLVlXsO9p88/EL566XdnycOWdhTGmNWMAwx4SKp5/za244/P9u" +
                "AIo4JT2IGIYQpEAQZEEcJEIo5EI0zz1mA8eHIxilhh4ZNa6cJWsq/nZcuaL92ZXi93emz3grKq/cj4wAsFAD4jmBpgWHAC46lMgg" +
                "8usqJq8cWRAHiRAKuRAN6QT4sLL4cAwYGQRG8MfISsi486Tu1KUJ721Pmz4nYlyRNQFDLU7o+ji5f3OT4eEj2bsJUqIVS8yEEGRB" +
                "HCRSLureeVLp5qO6SSC/WMaHIzhFqM8eqFJPkTiVbOIm4+TFog3bUqe9Pio9X4eM3gpDFAtDJpLVW4TSvODo+Yvm8YKUGCPiX4V4" +
                "8YE4SIRQyIVoSIeASv3hU5969k8tL04dwS81etcmFFakT/etGAoZv5vVtzDRJEMOC2MgItRbfzK8+PBvRqDIIaISQrz5SMtFKIWP" +
                "nptCEBAZVdYvwSk+HEFOKL37GSzJKLwpr0iihEolZlhDhhYWxkCYhEMTFG1EAudj2uuIhnQIiIyIqbL/EYTk4rAqoWiRMTq7OGPW" +
                "OyzZWZhRflNkkUqNs4lwwNDEQtOpKT7NnwwPHyl+zZASVUREQohBfkE0pENAZERMJFXZP9XjY+Dg0EoovkVoWEp2atvsks273M8I" +
                "sTyjCPerQA2LDME8ooNFik6TgUMXFDVEdLOMWAniqU+RDgHdT2EhKcJ6rr/4FqdWJRdH8EqNkZFJyU1theu21p++3Hz9kXNnJ8v3" +
                "vlWrX8wwTiXSWKQYNi0yxPhQo8QQEYkU4xU/kA4BkRExkRRhkddz/TYoxYcjeAmFujp32bqaw11T7/1csf+YUkn9utMlRIZ6hWEV" +
                "FiGRY2j6cLiPsRoR3RSjywcCKnX9/mPKpajDXcirsXixJrk4gpBQeu/coW6atPeIcpnxyNm85esTql0myRitS4YwFm5P+zQROHya" +
                "PCIiVYgoH8iImEiKsMiLyCr3B1mUXBzBCBuhSVlp098o7djTdOVeQ9e1ovUdKa6X/K6biJPhn0oksFB1sAgZOnwYUaKHiFCKUeXD" +
                "c/0FMZEUYZEXkZHac3+hxcHDEUjY0EooiXUtBas3kxdd3d+Wfbhv7Ctv+i1cddYmYqkkMCwsgUMCEdEUY7R+8SxukRRhkReRkRrB" +
                "jZOLfPBwmAobeiuUqMJJ2fNXVHaeaH34S+WB49lvL++7P8N6MswwERKZShMhw8NHak8zR0lQ+EBShEVeReTOEwjuuX9dZOViPRxi" +
                "CSUxgyhXtm1v81cP605eLGjflFDbbBEZxgHDEIj+TR6O/k0KEcMUY4YPhEVeREZqBFeSS+/zL5YlF4e1dWh8dVM+Mz71peva/dIP" +
                "9qS1ze6728+g1AgSGamqTZwMbT40KbGSD+3iA2GRF5GRGsGRXbksZ2ll6rAwbIzOKsqcs6hi39HWB/+p/OQEca/vDmHxItSYDLNY" +
                "RPU1aTj6nWsBIsZ8CBWnyKskl09OIDiyI77n+UprgofDompDuSKf3NQ24b0dky/ebjjbXbh2a2J9i3RCsYYMTSZCotLcTR6ONE/T" +
                "oSR4fGgmF0RGagRHdsTHBb7X9AOoPBxWhY1IKJ6/svofp1vuPnHuOpg+c17f8yb+YcMKMmSwSOvfZMnw48ObEmlEAuejDw5ERmoE" +
                "R3bExwXK8/sWBQ+HJWFjRERiSsuMkq27Xd0Pnj/xRd7y9XHOenOlhjVkaGBBCzULR6hfV9qIBMKHdPGB1AiO7IiPC3CE5/0fgQYP" +
                "hyV7G1FFFeMXrao5+q8pN79j/U2h1Pv0okpCESw1pMgwxiLU08yR8Ssf7mYCERE+DIsP1eSC1AiO7IiPC3CE54J+oHseDlM5xTds" +
                "jJk6s7RjT/ONR7WfnstZvDqmuMqChGKeDHUsQqPG0gKDY2xP00XEJB8BJRcER3bExwU4AnfoBg/RzOKwIGwUTBy/sL3n5SqPSzs+" +
                "Tm19rfdZeMGEYgkZagHDB4vQ6IDI6OUjeqwuIv4hxFI+NJILgiM74uMCJXgsbMcpgQcPR4BhQ1mkNL9csuWj5q8e1h77HH6jJ1Sa" +
                "CBsapYYUGXpYuJs1cLibISJSfBgUH8bBA9mV4HHscxyBO3CK7rJFKHg4AixFR2cXj3v7XerkF2//ULZ9f+q013svsJkMG5qlhiAZ" +
                "WlhYQoYvH3qIiPMhWXxoBY/oMYiPC3AE7sApnlvFzJeljgBySu81tqKNH07+8k7dqUvUzLFltYGGDQvI8MWip6VbB0e6b+f9EAmY" +
                "D/PBA/FxAY7AHTjF92qcfGZxBJJTwpLHZcx6x70lOnH3ofRX5/ZulpsOG5aQ4YeFu1kKR7oGIpbxYSJ4ID4uwBHuDVNc43l/ssnM" +
                "4hDMKaqlaAyortxYf+Zq44VbhWu3+t3Ooxo2RBKKTqkxyGRYyIdh8aHLh8bVuGoXjsAdOAXX4CCxslQODo2c4lWKxqW0zCjbtpck" +
                "V/X3k+PmLu1766Nw2JBMKFJkpPdvQYPDDxHzfMgkF//g4Xm/JY7AHUoJuG0vDvK8n/9XPiQyi8N0ThmVUZD11jJqnym3vi/9YE/K" +
                "lFcsDxtWkREaYzUcMelB5COw4IEjcAdOwTU4SPn+BrOZxWE6p8RNeqFg9ebG8zfrP7uSt2KD383DqluiAYcNM2Rk0KyGQ+kzAD6s" +
                "CR7qG2KlNbgDp+AaHISbTGcWh7l1ClMZ0/pa+Y4DLd/8VHngeObsBb1vlxZZpAQaNnTI8A0YuDCsp1kLh7vPHkS0Q4gqHxYED4Nl" +
                "C47AHTgF1+Ag3OT1bL7MmsVhLqeEp+dlzV2q5JSb35Vs2Z3cNF02p+iHDcOEIkVGkOCQ50MkuUgFD/XMgjtwCq5RMsvcpTjLXGZx" +
                "mNv7ogzO/+OflW+/6rqWT1WsllPESlHhsGFAxlifVBLm3YIERx8iovlFOLn4Bg/DstQrs+AUXIODcJPqmkVkN8whX3Ao+yrJTW0l" +
                "W3dP+fp7CuOs3y/uvbncXCkqETb6JxQJMsJiMq2GI1OWD5nkIrXnoRI8cAdOwTU4CDcpdwAJ7YYZw2G8iA2JS0ufMa9i39Gp934u" +
                "/+uBVCWrxZvKKVaFDR0yMt0tCHBk+iCiyUdwg4daZgmPxym4RnnWcN9RnOX5/kq5Ba3DRMExOrs4e8Efao+fb7p8t2h9h+rel3ZO" +
                "kdoSFQkbXnWGKhlhsVbDEZupwYde8aEfPIQ2TIUzC07BNTgIN+Es3essmmWHGThinXUFq/7SeOFW3alLuUvWeN9FLLlOsTBsxPiE" +
                "jT4yggKHGh9+9aklwUNyzeK59xjX9HyX5S2chcushUOz4EhqnFay5SOl4Dj4z8w5CwUWseZyimzY0CQjLDbLajiy9PiwMHiYzSzK" +
                "gnbOQhyklB1bPsJlJsoOaThGRCSmTX9Dubrz8Bfnzs7Uaa/3fsOe9N6XWCmqFzaMSg0PGcGBw4cPo+JDOnioZhbh3bBRCbgGB+Em" +
                "nIXLvO4NsxIO7/exZM5ZVHXoVPONx8Xv70xqmCpacJjPKUZhQzWh9CMjaHCo86GfXNSCR2CZRaPswDU4CDfhLFzm+6YXeThUlype" +
                "BUdETsn4RauUb/++8LU7mRkVHIZ7X0I5RThsqJARTDi0+RAJHqKZRXI3zH17R29p+DXOwmU4Tq/sUFuwOGSrUWWDpX2T8pXupy7l" +
                "LF4dmVtmVcEhkFNMho1wq+EIF4HDOHiIZRazZQeuwUFKTXr+Ji7DcbI1qTQc8TWuCRu3u7of1Bw+M27uUtntL/mCwzCnGJMRHjvO" +
                "ajjGhcsFD3OZRbzsUN8Kw0G4CWfhMhxnFRyqG+e9e6OlHXuUd6buP5Y+c57q8ykyOxxCBUcgOUWBI85qOOJk4TDMLDJlh1hNimtw" +
                "EG7CWbhMdZ9UfxPdIbeODYsd0zrLuauz9dF/nbsOKksV9b3RAKtR1YJDPaeIkBEUOIT4EMgsMmWHTk2qvk/KgmXXwR5ndeI4r/vR" +
                "BRYscnCMjE4Z++rcin1HW+7+qNxo5HopOEsV8YLDMGyMCyYc4wLOLCplh4ULFhyEm3AWLsNxuC+IcIQmZmTMXqBsrdz8jmWS6nP0" +
                "Onuj8tWoZMGhETaCBYdm8LC67NCsSVX3Sb2ewcdNOAuX4Tivt7tYA0f/2zhSc7KUGqfLde1+0YZt8VVNptaxcnBoFhxe65TMoQRH" +
                "pt6aRa7sMLtg6fELDsJNOAuXKTd2pOZIbXXIwTEqoyB7/ora4+cnX/p34Zot3o/SDwIcgjklmHCMky47BhAOHISbcJZy+W3+Cr/7" +
                "SQOFw/d67PiF7T07YLcKepbOJuGIkIdDshrtHzaCCIdX8BCvSSXhiDAJBw7CTcol0pMXcZzBtVldOES2R0tzlqypP31ZucVo5Ubv" +
                "x2KDCod4NZqlBke21XBka2YWEzVp0ODAQbgJZ+EyHIf7pDZJ5eCIzCvPXba2/szVhrPdecvXe79D0io4Up9VOFKth6NwEm7CWbgM" +
                "x3nedRwkOPKducvWNXRdo+W9+6eogok2HEMZDhyEm9z+wnGqb4Sy4bDhGAA47LRipxW7ILULUnspay9l7U0wexMsOJtg9va5vX1u" +
                "X3izL7zZl+ztS/bBgsO+2ce+2ce+TdC+TdC+wdi+wdjau8/tRxOe7UcT7Iea7Iea7Mch7cch7Qep7Qepg/ogtf0KBvsVDPbLW+yX" +
                "t9ivfbJf+xQIHPYL4+wXxtmvmrRfNWm/pNZ+Sa31L6m1X29tv97afjG+/WJ8YTiG4Vdq+CSC/z1WJdVU8siz+pUaw/DLeHwQMQ1H" +
                "qGHAeFa+jGcYfY2XPyKyZGhj8cx9jddw+wJAf0rE4dBm4hn9AsBh+NWhPk0CjmjryRgWXx06jL502Bwfwlg8W186PNy+rtyfEnk4" +
                "xupg8Ux9XblQZvltWGxy88slWz5q/uph7bHPcxav9n6A1lTwECo+NPkQQ6QXFAEyNM7VxEKKDJVSw1zYQHbExwU4AnfgFK97zeVz" +
                "ihgcRmVpVMHE8Qvba47+q/nG49KOj1NbX3suKiWA4KGZXAT4kEbECA5TWMiSoZJQJMNGVAqyIz4uwBG4A6eIlaLm4RAKHiMiEsdM" +
                "nVnasaf5xqPaT8/Bb0xxlYngESgfaiFEBZEos3BE6WPhHzCsJkM7bCC4EjY+PYcLcATu8Lrvy1TYEIbDMHgUVYxftApmp9z8ruzD" +
                "fWlts1WfZ/HbMDVTfIjxoYNIP0p6miYZ3of17yHEOGBIkZEsRkb/LVGv51MQHNkRXwkbi1bhjsDDhggcQmUpnKa0zCjZutvV/eD5" +
                "E19QM3s/gC+QXAyKD0M+hBDxo0Rp2nD4HhliCgtBMtRKDeOE4n6UHsGRHfFxAY7QDRtRgmFDFg694BGZ78yev5I6ueXuE+eug+kz" +
                "54Wn5liQXEzzoYtIf1D04QjRbKpYBEiGdEJBZKRGcGRHfFyg+m4nEzlFEA6h4KEsW5raJry3Y/LF2w1nuwvXblV9Bt9aPiQR0aTE" +
                "nwxjJsxgYQkZvs/RIzWCIzviK/f16C1SJMKGCTj0gsforKLMOYvcG6aVn5zIfnu5973HOsnFcj78EPGlJFUGjlRdJlJVJ2AdGZph" +
                "A3kRGandW6KIjwusChuScBgGj9CY+Oqm/PZNdae+dF27X/rBHgql3g11+eJDl48AEFEHJdWbjFQBIExhIUSGUKmBsMiLyEiN4MiO" +
                "+F5bonphw0o4RINHaGJG2vQ3yrbtbf7qYd3JiwXtmxJqm6WTi8V86FLiaV5wGB2sM5CVZOgmFIRFXkRGagRHdq93swQcNqTgEKk8" +
                "epa1hZOy56+o7DzR+vCXygPHiXveb6QMhA/jFGOEiCYoAnAYdKs6GS0sAiQDSZWEcuC4InLnCQRHdi8yAqs2zMJhtOfhvhpXsHpz" +
                "/enLru5vWX+PfeXN3tvTg8JHsoZXRCjxIqYfGRInao2uEzACJAMxkRRhkReRkdr3GlsAexum4RBOLklZRLnSjj1NV+41dF0rWt+R" +
                "4nqp94KcVHHajw+jFGMBIh44LMVCM5Xok6FZaiAjYiIpwiIvIisJJSnL2oQSABwClWlkXnnW3KWT9h5p+eanmiNn85av97sVSIoP" +
                "wRCSrO2wFKvg0BlCHwuvgCFLRr/beRATSREWeRHZ815iy+pQ03CIBg/lDuSKxtxl62oOdynPXe0/lj1/pd9NyMJ86KcYGURMRBSR" +
                "3jSwEEklEmQgIDIiJpIiLPIisnFCMRU2AoBDJXj48jEyMim5qa1w3VbyYvP1R86dnZlzFkbllcvwIZJiAkLEiiaOhW4qMSID6RAQ" +
                "GRETSREWeRFZlwzzYcMcHILJpfdNL6lts0s272q8cGvypX+XdnycPuOtiHFFesWpb32qmWKEEUkeCCZEsDAgI16nCEU0pENAZERM" +
                "JEVY3/exWJdQAoFDIrmMzi7OmPVO+Y4Drqv3Xzh3vfj9nWnT54xKz9eKHyMM+dCrQvQRCRwUjT7VsNCtMFTIGKEdM5AL0ZAOAZER" +
                "MZHUc6NXUBKKFXCI8RFVVEHdNHH3oeabj+s/uzLhve2p0173W9z6h5AEAUSSDBDRoyTgNtoQiyQBLIzISMtFLkRDOgRERsT0XJQX" +
                "JGOg4ZAoPpSHGMqfVyqpfUdfvP1D3alLRRu2pf5ulkV86CDiTcloy4FI9h9xpFzAECDjd7OQC9GQDgGVur78eSMyogInI0A4VJJL" +
                "X/GhtngZv2hVxd+Ov3jnSd3JiwofxA/D/KKSYgwQ0aDEDxRDYrSOV+t8pCwWOkVGv2yCRAoZJy8qbwX+23EE1Fie+JUaIYGSYREc" +
                "xsml95p+fHVTzpI1lW4+Tl0iVJJK/erTOG+9tEKIFiIilOiyIkaDJhNCWPgHDF8ykAVxkEiJGXeeIBrSKZfWfK7IByehWAKHHB9Y" +
                "Hl/jwkglftz+gSRKkUUR3re+DQuMD41AYkSJdBspFCrkyQjrW7UiC+IgkZJN3GTUuLyelw8yGZbAIV58ePioblLyy76jlFeU3yzP" +
                "WL737Y8FHkJ0Y4kJXEaqt0RdJkwGDPdOF4IgC+IgEUIhF6IJkBFlIRlWwSHHB4GRxElhReHNwoyFu3NnJ78mVLv8rr+o8qGFiAgl" +
                "iSM1nS3SEs0w4cHCkAzMRwSkQBBkQRwk4lelzjDOJhaTYSEcOsWpGh896xeWZCzZGy/car7+qGL/sbzl61NcL/UtYSxHRJ0V4WbY" +
                "bQBYuBcmmI8ISIEgyII4SKSyNtEiI8RKMoIAhwwfLNYzZr1TsnlX/enLysWCI2eL1neMfeXNvvs/tPkQQEQMlECb9tCaWKiQgckY" +
                "jvmIgBQIgiyIo7KfYUzGUITDDB+js4tT22YXrttac7ir5ZufGrqulX24L/vt5Qm1zX33F1qASMLAMSGJBWZiLCZjOOYrF7EPdyEI" +
                "sqjsgQ4gGZbDYYaPsJTs5Ka23GXrJu090nTlnqv728oDxwvaN6W1ze67P9mLjzg10cUpkSVGuDc9JuK95h/Wd4cwZmIsJmM45iMC" +
                "UiCI57rJoJERDDjM8DEyMomai/xa2rGHiNr68Je6kxdLP9jD5ymxvqXv+RcJRGQpCaB5mJDCAqMwDQMxE2MxGcMxHxGQwnOtdTDJ" +
                "CBIcAnyoIRKZV542/Y2C1ZsrO080f/XQde1+5ScnCtduTZ85L85Z3/t8pRgivpSEBwMIQybUscAQzMEoTMNAzMRYTMZwzFe5c6ff" +
                "HuhAkhE8OEzyEZqUlVjXkj1/Rdm2vXWnvmx98J+Gs93OXQep4Qm/McVVvc/vqyASp+2h/qB4WAk3gUJC/35GCDLRDwsmjwkYgjkY" +
                "hWkYiJkYi8kY7rnbb0iQEVQ4DPlQTzHu+9f5DOW3b6rYd3Tyxdstd588f+IL6rWcxatTW1+LnlDZtx0iSYkGLsZthFBTZ8K9gcG0" +
                "mTwmYAjmYBSmYSBmYqzn3nHNVDLwZAQbDk0+tEsQTwhJzIivbsqcs2jCezuq/3Ha1f1gys3vaj89V9rxsYLItNdjy2q9ljMqiMSN" +
                "EHVqgC1OBwsmyVSZMNNm8piAIZiDUZiGgZjped4kxlcKlYAxcGQMABz9+JBIMZ6FblYRdXv2/JUlW3f3vBzmUfONx7XHPi/bvp/I" +
                "nP7q3IRqV9/7LfUoiQs6EN5MuN/6yPSYJFNlwso7d248xgQMwRyMwjTP04uqWBimkshg+24A4BDhQzOE/DYsNjLfmdIyY/yiVRTz" +
                "CiJfPXTfFDJx9yFqunFzl6ZMeSWmtKb3/dpCoEgRo9uD34hMg8kwJSbG9Jik+1YMps3kMQFDMEd5Fr53R1wzYAwuGQMGh3CK0UBk" +
                "RERiVFHFmKkzxy9sL9nyETF58pd3qOYaL9yq+vtJVoN5KzZkzl6Q3DQdxygb8O7vf5EDRbip9BzPoAzNBJgGk2FKTIzpMUmmyoSZ" +
                "NpPHBAzxvD9DMGAMaCoZLDj8+RAMIf0QKZiY3PzyuLffLdr4IdVc/ZmrfCin3Pq+/rMrlQeOl2zZnb9yY9bvF1P6EdKj8p1KOHF/" +
                "P6HlbVQCnTMEAzEcgzI0E2AaTIYpKfcknLnKJJkqE2baTF4TC/2AMRhkDDwceinGKIT0JZrR2cUs/DJmvZO3ciPrQD6Xjedvtnzz" +
                "E7VeQ9c1PrLlfz1QtL4jd8mazDkLKQaTGqbGOusic8v4fCv7JapxRb+Fx3Mip9MJXdEh3dI5QzAQwzEoQzMBpsFkmBITY3pMkqkq" +
                "G+FaSUQiYEQOsLMGHg5BPowQ6Xl/ckxZLfk7661lBas3l+84gEteOHd9ytffT733c9PluyT7qoP/dO7sLH5/Z8Gqv7BeoA5InzkP" +
                "v6a4Xkqsb4mvaopz1pMOWGdGF07ik03jB37lj/yLAziMgzmFEzmdTuiKDumWzhmCgRiOQRmaCTANJsOUmBjT87xD2BiLoUbGYMFh" +
                "JSK/DYsblVEQN+mFMcT2uUvz//hn1gIE89rj50n5+Kz14S8sE5QvZj51qebwmYr9x5y7DvKxxsFFG7YVrtlS0L6JjMCaIu/dPylt" +
                "+Xp+5Y/8iwM4jIM5hRM5vef7Fr+mQ7qlc4ZgIIZjUIZmAkyDySjfVdD7RvqnEotBh0OVD1lE+iihVAxPz+PDyhIxfca87AV/4CNO" +
                "Gch6oerQKeX71c/fdHU/ePHOk9ZH/225+6Oy33DtvvsZIeX7yM52kxeUdrabX91PYXGAkinu/sgpnMjpdEJXdEi3dM4QDMRwDMrQ" +
                "TMBzv5YGEyJYDA0yBh0O4xAijEi/WNLz/ZWkeaU4aJyWNv2NzDmLWEDmt2+asHE7i0nnrk4+6ySFmsNdfO5xdv3pyxSPbjj4gV/5" +
                "I//iAA7jYE7hRE6nE7qiQ7qlc4ZgIM93L+oyYYBF1JDCYujA4c2HICJilLjXOCwrInJKKCPia1x8xMe0zhr76tyM2QvIAtnzV7DC" +
                "zFmyJnfZ2txl63raWn7lj/yLAziMgzmFEzmdTuhKWQT1rTsEmZDCInIo+GWIwCGUZbwRMQwkKqD8ut4ZGZ0SmpgRnppDccBHPyKn" +
                "NDKvPDLfqbS8cn7lj/yLAziMg/utNcSAUAsVmliEDDkshiAcooioU2IMijYuok2g/xARJoY6FkMWDh1E9AOJLCWWNjUm9ELF0MZi" +
                "iMPhV4hIBBJvUEKCTUO0/+jCoWLokjHE4dAvV9Up0QDFmxUpaFRPVBviN/pMhDw1TDxdcBgGkkgNx2iBIsCNBgFiQOgzEfm0aP4U" +
                "waGBiBgl8sSIcyDOROTTpfZTB4c4JaKsBNb8Rnz6mRgGcOhSog5K4Lho9PncsGJiOMFhRIkxLpLNcKDhIulwgkMGFOvbMJRxuMIR" +
                "bFyeCdGeHThk0bE1seGwmw2H3Ww47GZl+39CFCr5/LkHGgAAAABJRU5ErkJggg==");
            ContentTypes["/icon.png"] = "image/png";

            Content["/favicon.ico"] = Convert.FromBase64String(
                "iVBORw0KGgoAAAANSUhEUgAAALQAAAC0CAIAAACyr5FlAAAk30lEQVR42u2d+XNUVdrH+7cZMAtk30nIQshOtoasJjGkgyFDcAER" +
                "GRGFYhWYCdsADg5gEKZAClnGMEwBQjGAhEEQZIksMiDIomWhVo3zw/sPvPX+Be/nptMm3X2Xc27fTkK4VeeHLPeec57v8+nnec65" +
                "Szt+81yE3eym2hy2BHaz4bCbDYfJFunXbE2eITgiLW02HDYKzzYujmcIiBCL2jMDimPYMqHp3agAmiwuNhxDhwmLUTCFyzCixDHs" +
                "mDD26G9NNWlWnn5KHE8xFgJMiDk+WqMFQow+JTYcQcLCiAkJAkIFmjA38pTYcAQlVIgAIQmBbNNlRY+SpyeQOJ4CMrRDhSYQoQPe" +
                "NEARDiQ2HOax0A8VUkzEBNBMUiIcSGw4AsBChQkTKITFjoxOCU3MCE/NGZVRMDq7OCKnNDKvPDLfqbS8cn7lj/yLAziMgznFDC7G" +
                "lAxpRBxDuOTUwsIwTnj5b0REYlhKdkROSUxpTXyNK7mpbUzrrLGvzs2YvSBr7tLs+SvGL2zPWbImd9na3GXretpafuWP/IsDOIyD" +
                "OYUTOZ1O6IoO6VYUFL9Yoo7I0CtEHEMyYOhiIcBESFwaH/1YZ11S47S06W9kzlk0ftGq/PZNEzZuL+3Y49zVWbHvaNXBf9Yc7qo9" +
                "fr7u5MX605frz1xt6LpG4wd+5Y/8iwM4jIM5hRM5nU7oig7pls4ZgoEYToYScUSeaTgM8ogYFp4IER4Xnp4XU1bLRzx9xrzsBX8o" +
                "WPWXki0fTdx9qOrQKZzdeP6mq/vBi3eetD76b8vdH6fc/M517f7kS/9uvHDrhXPXG852u+HgB37lj/yLAziMgzmFEzmdTuiKDumW" +
                "zhmCgRiOQRmaCTANA0r0EBlaWcYxNAOGABa/FhBxFAdxk14Y0/oaWSD/j38u2bqbzzqfexw85evvWx/+0nzjceOFr+tOXao5fKZi" +
                "/zHnroNl2/YWv7+zaMO2wjVbCto35a/cmLd8fd67f1La8vX8yh/5FwdwGAdzCidyOp3QFR3SLZ0zBAMxHIMyNBNgGkyGKTExPUoM" +
                "ERkCfDieXizCksfxYU1pmZH11rKC1ZvLdxyo/sdpPvT4bOq9n5su38WRJAXnzk4czEc8Z/HqcXOXps+clzrt9RTXS4n1LfFVTXHO" +
                "esqI6AmV0YWTogom0viBX/kj/+IADuNgTuFETqcTuqJDuqVzhmAghmNQhmYCTIPJMCUmxvSY5NOLiGNIkqGLRVgsaT6xriVj1jt5" +
                "KzfyscYlRPuWb34iBZAXqv5+svyvB4rWd+QuWZM5ZyF+TWqYSnEQmVs2Ki03JG7siPD4EWFxci08nhM5nU6UUqZhKt3SOUMwEMMx" +
                "KEMrOeibn5gMU2JiTI9JMlUm3G+9o4fIkOLDMThk+FUYXgFDAwsWCHyyk5tfHvf2u0UbPySYUzy+ePuHKbe+r//sSuWB4yVbdpMR" +
                "sn6/OLX1tYRqV1S+U1lWjEqQRkGkjUqgc4ZgIIZjUIZmAkyDyTAlJsb0mCRTZcJMm8n3W+OoIuIfQvyrkOEJh7mA4cGiqGLM1Jms" +
                "MCkD+VxO/vJO64P/kPL5yJZ+sCdvxYbM2QuSm6aTDvh8q8eGcIuaWlxhUIZmAkyDyTAlJsb0mCRTZcJMm8ljAoZoIiIaQoYVHJqp" +
                "RDdg9CaRyHwn+ZsFJIvJmqP/av7qIR9Kkj3rhcK1W6kDUqa8gmOUICENRLxAkwOFaTAZpsTEmB6TZKpMmGkzeUzAEMzBKM1EoxNC" +
                "BjbFOIYAGZoBY3RWEUvE7PkrWQsoWNx4xDKh9tjnZdv3s6ZIf3UuIX10ZoEYEPGWNmNQmBjTY5JMlQkzbSaPCRiCORiFaRgoE0IG" +
                "mg/H4KcSNSxCEzPiq5sy5yya8N4OYrKr+wG1Xu2n50o7Pma9QDEYW1YbmpBpxET8gDQ9SpgkU2XCTJvJY4Kyv9L9AKMwDQMxE2P1" +
                "Q8hgpRjHwJOhnUp6l3xRhZPSpr+R376Jam7yxdstd588f+KLsg/3KVi0vsY687noMbpYGHt0pGQzQ0m/GTJhps3kMQFDMAejMA0D" +
                "MRNjMVl9xSuUYp4+OGRTSU/ASMpi4Zc9fwXrwLpTX1LNNZztdu46SGROa5sdU1z1XFSKCSa8PZ3Q20YJt19PEcVFnRImjwkYgjkY" +
                "hWkYiJkYi8kYjvkafEQPCh+OoUNGZF45n6GC1ZsrO09Qvrmu3a/85AQ1XfrMeXHOemV/Qh0LQyAkUZDAxRAUFUQwBHMwCtMwEDMx" +
                "FpMxHPMRYejw4RgEMvywGBmZFFfRmDV3KcV8/enLrQ9/qTt5kdVg9tvLE+tbwlNzxLHwYmLUgDRjSlQQwShMw0DMxFhMxnDMRwSk" +
                "QBCdFDNgfDgGnQzWftTtucvWTdp7pOnKPVf3t5UHjheQidtmR+U75bGQcm2iQJOmRBwRDMRMjMVkDMd8REAKBEGWQefDMbhkjM4u" +
                "Tm2bXbhua83hrpZvfmrouka9xucpobbZazGijYUwE4mWNtOU+PKBmRiLyRiO+YiAFAiCLMqm+6Dy4RhEMqKKKjJmvVOyeRcRdeq9" +
                "n2uOnC1a3zH2lTejCydZh0VikJs1iGAyhmM+IiAFgiAL4iDRIPJhNRzCZMSUP09+Ld9xoPHCrebrjyr2H6OGT3G9pGx+G5FhhIWR" +
                "R0ebauZA0UTElw8Mx3xEQAoEQRbEQSKEkudjaMHRP2wYkREWS82VPX/lxN2HXFeV222cOzv5NaHa1beBYS0WXm5O0mo//s//0XQO" +
                "EGPFPCKYjwhIgSDKrUZX7yMRvyKXZ6/diA9Lg4djgMlAiPjqpvGLVlXsO9p88/EL566XdnycOWdhTGmNWMAwx4SKp5/za244/P9u" +
                "AIo4JT2IGIYQpEAQZEEcJEIo5EI0zz1mA8eHIxilhh4ZNa6cJWsq/nZcuaL92ZXi93emz3grKq/cj4wAsFAD4jmBpgWHAC46lMgg" +
                "8usqJq8cWRAHiRAKuRAN6QT4sLL4cAwYGQRG8MfISsi486Tu1KUJ721Pmz4nYlyRNQFDLU7o+ji5f3OT4eEj2bsJUqIVS8yEEGRB" +
                "HCRSLureeVLp5qO6SSC/WMaHIzhFqM8eqFJPkTiVbOIm4+TFog3bUqe9Pio9X4eM3gpDFAtDJpLVW4TSvODo+Yvm8YKUGCPiX4V4" +
                "8YE4SIRQyIVoSIeASv3hU5969k8tL04dwS81etcmFFakT/etGAoZv5vVtzDRJEMOC2MgItRbfzK8+PBvRqDIIaISQrz5SMtFKIWP" +
                "nptCEBAZVdYvwSk+HEFOKL37GSzJKLwpr0iihEolZlhDhhYWxkCYhEMTFG1EAudj2uuIhnQIiIyIqbL/EYTk4rAqoWiRMTq7OGPW" +
                "OyzZWZhRflNkkUqNs4lwwNDEQtOpKT7NnwwPHyl+zZASVUREQohBfkE0pENAZERMJFXZP9XjY+Dg0EoovkVoWEp2atvsks273M8I" +
                "sTyjCPerQA2LDME8ooNFik6TgUMXFDVEdLOMWAniqU+RDgHdT2EhKcJ6rr/4FqdWJRdH8EqNkZFJyU1theu21p++3Hz9kXNnJ8v3" +
                "vlWrX8wwTiXSWKQYNi0yxPhQo8QQEYkU4xU/kA4BkRExkRRhkddz/TYoxYcjeAmFujp32bqaw11T7/1csf+YUkn9utMlRIZ6hWEV" +
                "FiGRY2j6cLiPsRoR3RSjywcCKnX9/mPKpajDXcirsXixJrk4gpBQeu/coW6atPeIcpnxyNm85esTql0myRitS4YwFm5P+zQROHya" +
                "PCIiVYgoH8iImEiKsMiLyCr3B1mUXBzBCBuhSVlp098o7djTdOVeQ9e1ovUdKa6X/K6biJPhn0oksFB1sAgZOnwYUaKHiFCKUeXD" +
                "c/0FMZEUYZEXkZHac3+hxcHDEUjY0EooiXUtBas3kxdd3d+Wfbhv7Ctv+i1cddYmYqkkMCwsgUMCEdEUY7R+8SxukRRhkReRkRrB" +
                "jZOLfPBwmAobeiuUqMJJ2fNXVHaeaH34S+WB49lvL++7P8N6MswwERKZShMhw8NHak8zR0lQ+EBShEVeReTOEwjuuX9dZOViPRxi" +
                "CSUxgyhXtm1v81cP605eLGjflFDbbBEZxgHDEIj+TR6O/k0KEcMUY4YPhEVeREZqBFeSS+/zL5YlF4e1dWh8dVM+Mz71peva/dIP" +
                "9qS1ze6728+g1AgSGamqTZwMbT40KbGSD+3iA2GRF5GRGsGRXbksZ2ll6rAwbIzOKsqcs6hi39HWB/+p/OQEca/vDmHxItSYDLNY" +
                "RPU1aTj6nWsBIsZ8CBWnyKskl09OIDiyI77n+UprgofDompDuSKf3NQ24b0dky/ebjjbXbh2a2J9i3RCsYYMTSZCotLcTR6ONE/T" +
                "oSR4fGgmF0RGagRHdsTHBb7X9AOoPBxWhY1IKJ6/svofp1vuPnHuOpg+c17f8yb+YcMKMmSwSOvfZMnw48ObEmlEAuejDw5ERmoE" +
                "R3bExwXK8/sWBQ+HJWFjRERiSsuMkq27Xd0Pnj/xRd7y9XHOenOlhjVkaGBBCzULR6hfV9qIBMKHdPGB1AiO7IiPC3CE5/0fgQYP" +
                "hyV7G1FFFeMXrao5+q8pN79j/U2h1Pv0okpCESw1pMgwxiLU08yR8Ssf7mYCERE+DIsP1eSC1AiO7IiPC3CE54J+oHseDlM5xTds" +
                "jJk6s7RjT/ONR7WfnstZvDqmuMqChGKeDHUsQqPG0gKDY2xP00XEJB8BJRcER3bExwU4AnfoBg/RzOKwIGwUTBy/sL3n5SqPSzs+" +
                "Tm19rfdZeMGEYgkZagHDB4vQ6IDI6OUjeqwuIv4hxFI+NJILgiM74uMCJXgsbMcpgQcPR4BhQ1mkNL9csuWj5q8e1h77HH6jJ1Sa" +
                "CBsapYYUGXpYuJs1cLibISJSfBgUH8bBA9mV4HHscxyBO3CK7rJFKHg4AixFR2cXj3v7XerkF2//ULZ9f+q013svsJkMG5qlhiAZ" +
                "WlhYQoYvH3qIiPMhWXxoBY/oMYiPC3AE7sApnlvFzJeljgBySu81tqKNH07+8k7dqUvUzLFltYGGDQvI8MWip6VbB0e6b+f9EAmY" +
                "D/PBA/FxAY7AHTjF92qcfGZxBJJTwpLHZcx6x70lOnH3ofRX5/ZulpsOG5aQ4YeFu1kKR7oGIpbxYSJ4ID4uwBHuDVNc43l/ssnM" +
                "4hDMKaqlaAyortxYf+Zq44VbhWu3+t3Ooxo2RBKKTqkxyGRYyIdh8aHLh8bVuGoXjsAdOAXX4CCxslQODo2c4lWKxqW0zCjbtpck" +
                "V/X3k+PmLu1766Nw2JBMKFJkpPdvQYPDDxHzfMgkF//g4Xm/JY7AHUoJuG0vDvK8n/9XPiQyi8N0ThmVUZD11jJqnym3vi/9YE/K" +
                "lFcsDxtWkREaYzUcMelB5COw4IEjcAdOwTU4SPn+BrOZxWE6p8RNeqFg9ebG8zfrP7uSt2KD383DqluiAYcNM2Rk0KyGQ+kzAD6s" +
                "CR7qG2KlNbgDp+AaHISbTGcWh7l1ClMZ0/pa+Y4DLd/8VHngeObsBb1vlxZZpAQaNnTI8A0YuDCsp1kLh7vPHkS0Q4gqHxYED4Nl" +
                "C47AHTgF1+Ag3OT1bL7MmsVhLqeEp+dlzV2q5JSb35Vs2Z3cNF02p+iHDcOEIkVGkOCQ50MkuUgFD/XMgjtwCq5RMsvcpTjLXGZx" +
                "mNv7ogzO/+OflW+/6rqWT1WsllPESlHhsGFAxlifVBLm3YIERx8iovlFOLn4Bg/DstQrs+AUXIODcJPqmkVkN8whX3Ao+yrJTW0l" +
                "W3dP+fp7CuOs3y/uvbncXCkqETb6JxQJMsJiMq2GI1OWD5nkIrXnoRI8cAdOwTU4CDcpdwAJ7YYZw2G8iA2JS0ufMa9i39Gp934u" +
                "/+uBVCWrxZvKKVaFDR0yMt0tCHBk+iCiyUdwg4daZgmPxym4RnnWcN9RnOX5/kq5Ba3DRMExOrs4e8Efao+fb7p8t2h9h+rel3ZO" +
                "kdoSFQkbXnWGKhlhsVbDEZupwYde8aEfPIQ2TIUzC07BNTgIN+Es3essmmWHGThinXUFq/7SeOFW3alLuUvWeN9FLLlOsTBsxPiE" +
                "jT4yggKHGh9+9aklwUNyzeK59xjX9HyX5S2chcushUOz4EhqnFay5SOl4Dj4z8w5CwUWseZyimzY0CQjLDbLajiy9PiwMHiYzSzK" +
                "gnbOQhyklB1bPsJlJsoOaThGRCSmTX9Dubrz8Bfnzs7Uaa/3fsOe9N6XWCmqFzaMSg0PGcGBw4cPo+JDOnioZhbh3bBRCbgGB+Em" +
                "nIXLvO4NsxIO7/exZM5ZVHXoVPONx8Xv70xqmCpacJjPKUZhQzWh9CMjaHCo86GfXNSCR2CZRaPswDU4CDfhLFzm+6YXeThUlype" +
                "BUdETsn4RauUb/++8LU7mRkVHIZ7X0I5RThsqJARTDi0+RAJHqKZRXI3zH17R29p+DXOwmU4Tq/sUFuwOGSrUWWDpX2T8pXupy7l" +
                "LF4dmVtmVcEhkFNMho1wq+EIF4HDOHiIZRazZQeuwUFKTXr+Ji7DcbI1qTQc8TWuCRu3u7of1Bw+M27uUtntL/mCwzCnGJMRHjvO" +
                "ajjGhcsFD3OZRbzsUN8Kw0G4CWfhMhxnFRyqG+e9e6OlHXuUd6buP5Y+c57q8ykyOxxCBUcgOUWBI85qOOJk4TDMLDJlh1hNimtw" +
                "EG7CWbhMdZ9UfxPdIbeODYsd0zrLuauz9dF/nbsOKksV9b3RAKtR1YJDPaeIkBEUOIT4EMgsMmWHTk2qvk/KgmXXwR5ndeI4r/vR" +
                "BRYscnCMjE4Z++rcin1HW+7+qNxo5HopOEsV8YLDMGyMCyYc4wLOLCplh4ULFhyEm3AWLsNxuC+IcIQmZmTMXqBsrdz8jmWS6nP0" +
                "Onuj8tWoZMGhETaCBYdm8LC67NCsSVX3Sb2ewcdNOAuX4Tivt7tYA0f/2zhSc7KUGqfLde1+0YZt8VVNptaxcnBoFhxe65TMoQRH" +
                "pt6aRa7sMLtg6fELDsJNOAuXKTd2pOZIbXXIwTEqoyB7/ora4+cnX/p34Zot3o/SDwIcgjklmHCMky47BhAOHISbcJZy+W3+Cr/7" +
                "SQOFw/d67PiF7T07YLcKepbOJuGIkIdDshrtHzaCCIdX8BCvSSXhiDAJBw7CTcol0pMXcZzBtVldOES2R0tzlqypP31ZucVo5Ubv" +
                "x2KDCod4NZqlBke21XBka2YWEzVp0ODAQbgJZ+EyHIf7pDZJ5eCIzCvPXba2/szVhrPdecvXe79D0io4Up9VOFKth6NwEm7CWbgM" +
                "x3nedRwkOPKducvWNXRdo+W9+6eogok2HEMZDhyEm9z+wnGqb4Sy4bDhGAA47LRipxW7ILULUnspay9l7U0wexMsOJtg9va5vX1u" +
                "X3izL7zZl+ztS/bBgsO+2ce+2ce+TdC+TdC+wdi+wdjau8/tRxOe7UcT7Iea7Iea7Mch7cch7Qep7Qepg/ogtf0KBvsVDPbLW+yX" +
                "t9ivfbJf+xQIHPYL4+wXxtmvmrRfNWm/pNZ+Sa31L6m1X29tv97afjG+/WJ8YTiG4Vdq+CSC/z1WJdVU8siz+pUaw/DLeHwQMQ1H" +
                "qGHAeFa+jGcYfY2XPyKyZGhj8cx9jddw+wJAf0rE4dBm4hn9AsBh+NWhPk0CjmjryRgWXx06jL502Bwfwlg8W186PNy+rtyfEnk4" +
                "xupg8Ux9XblQZvltWGxy88slWz5q/uph7bHPcxav9n6A1lTwECo+NPkQQ6QXFAEyNM7VxEKKDJVSw1zYQHbExwU4AnfgFK97zeVz" +
                "ihgcRmVpVMHE8Qvba47+q/nG49KOj1NbX3suKiWA4KGZXAT4kEbECA5TWMiSoZJQJMNGVAqyIz4uwBG4A6eIlaLm4RAKHiMiEsdM" +
                "nVnasaf5xqPaT8/Bb0xxlYngESgfaiFEBZEos3BE6WPhHzCsJkM7bCC4EjY+PYcLcATu8Lrvy1TYEIbDMHgUVYxftApmp9z8ruzD" +
                "fWlts1WfZ/HbMDVTfIjxoYNIP0p6miYZ3of17yHEOGBIkZEsRkb/LVGv51MQHNkRXwkbi1bhjsDDhggcQmUpnKa0zCjZutvV/eD5" +
                "E19QM3s/gC+QXAyKD0M+hBDxo0Rp2nD4HhliCgtBMtRKDeOE4n6UHsGRHfFxAY7QDRtRgmFDFg694BGZ78yev5I6ueXuE+eug+kz" +
                "54Wn5liQXEzzoYtIf1D04QjRbKpYBEiGdEJBZKRGcGRHfFyg+m4nEzlFEA6h4KEsW5raJry3Y/LF2w1nuwvXblV9Bt9aPiQR0aTE" +
                "nwxjJsxgYQkZvs/RIzWCIzviK/f16C1SJMKGCTj0gsforKLMOYvcG6aVn5zIfnu5973HOsnFcj78EPGlJFUGjlRdJlJVJ2AdGZph" +
                "A3kRGandW6KIjwusChuScBgGj9CY+Oqm/PZNdae+dF27X/rBHgql3g11+eJDl48AEFEHJdWbjFQBIExhIUSGUKmBsMiLyEiN4MiO" +
                "+F5bonphw0o4RINHaGJG2vQ3yrbtbf7qYd3JiwXtmxJqm6WTi8V86FLiaV5wGB2sM5CVZOgmFIRFXkRGagRHdq93swQcNqTgEKk8" +
                "epa1hZOy56+o7DzR+vCXygPHiXveb6QMhA/jFGOEiCYoAnAYdKs6GS0sAiQDSZWEcuC4InLnCQRHdi8yAqs2zMJhtOfhvhpXsHpz" +
                "/enLru5vWX+PfeXN3tvTg8JHsoZXRCjxIqYfGRInao2uEzACJAMxkRRhkReRkdr3GlsAexum4RBOLklZRLnSjj1NV+41dF0rWt+R" +
                "4nqp94KcVHHajw+jFGMBIh44LMVCM5Xok6FZaiAjYiIpwiIvIisJJSnL2oQSABwClWlkXnnW3KWT9h5p+eanmiNn85av97sVSIoP" +
                "wRCSrO2wFKvg0BlCHwuvgCFLRr/beRATSREWeRHZ815iy+pQ03CIBg/lDuSKxtxl62oOdynPXe0/lj1/pd9NyMJ86KcYGURMRBSR" +
                "3jSwEEklEmQgIDIiJpIiLPIisnFCMRU2AoBDJXj48jEyMim5qa1w3VbyYvP1R86dnZlzFkbllcvwIZJiAkLEiiaOhW4qMSID6RAQ" +
                "GRETSREWeRFZlwzzYcMcHILJpfdNL6lts0s272q8cGvypX+XdnycPuOtiHFFesWpb32qmWKEEUkeCCZEsDAgI16nCEU0pENAZERM" +
                "JEVY3/exWJdQAoFDIrmMzi7OmPVO+Y4Drqv3Xzh3vfj9nWnT54xKz9eKHyMM+dCrQvQRCRwUjT7VsNCtMFTIGKEdM5AL0ZAOAZER" +
                "MZHUc6NXUBKKFXCI8RFVVEHdNHH3oeabj+s/uzLhve2p0173W9z6h5AEAUSSDBDRoyTgNtoQiyQBLIzISMtFLkRDOgRERsT0XJQX" +
                "JGOg4ZAoPpSHGMqfVyqpfUdfvP1D3alLRRu2pf5ulkV86CDiTcloy4FI9h9xpFzAECDjd7OQC9GQDgGVur78eSMyogInI0A4VJJL" +
                "X/GhtngZv2hVxd+Ov3jnSd3JiwofxA/D/KKSYgwQ0aDEDxRDYrSOV+t8pCwWOkVGv2yCRAoZJy8qbwX+23EE1Fie+JUaIYGSYREc" +
                "xsml95p+fHVTzpI1lW4+Tl0iVJJK/erTOG+9tEKIFiIilOiyIkaDJhNCWPgHDF8ykAVxkEiJGXeeIBrSKZfWfK7IByehWAKHHB9Y" +
                "Hl/jwkglftz+gSRKkUUR3re+DQuMD41AYkSJdBspFCrkyQjrW7UiC+IgkZJN3GTUuLyelw8yGZbAIV58ePioblLyy76jlFeU3yzP" +
                "WL737Y8FHkJ0Y4kJXEaqt0RdJkwGDPdOF4IgC+IgEUIhF6IJkBFlIRlWwSHHB4GRxElhReHNwoyFu3NnJ78mVLv8rr+o8qGFiAgl" +
                "iSM1nS3SEs0w4cHCkAzMRwSkQBBkQRwk4lelzjDOJhaTYSEcOsWpGh896xeWZCzZGy/car7+qGL/sbzl61NcL/UtYSxHRJ0V4WbY" +
                "bQBYuBcmmI8ISIEgyII4SKSyNtEiI8RKMoIAhwwfLNYzZr1TsnlX/enLysWCI2eL1neMfeXNvvs/tPkQQEQMlECb9tCaWKiQgckY" +
                "jvmIgBQIgiyIo7KfYUzGUITDDB+js4tT22YXrttac7ir5ZufGrqulX24L/vt5Qm1zX33F1qASMLAMSGJBWZiLCZjOOYrF7EPdyEI" +
                "sqjsgQ4gGZbDYYaPsJTs5Ka23GXrJu090nTlnqv728oDxwvaN6W1ze67P9mLjzg10cUpkSVGuDc9JuK95h/Wd4cwZmIsJmM45iMC" +
                "UiCI57rJoJERDDjM8DEyMomai/xa2rGHiNr68Je6kxdLP9jD5ymxvqXv+RcJRGQpCaB5mJDCAqMwDQMxE2MxGcMxHxGQwnOtdTDJ" +
                "CBIcAnyoIRKZV542/Y2C1ZsrO080f/XQde1+5ScnCtduTZ85L85Z3/t8pRgivpSEBwMIQybUscAQzMEoTMNAzMRYTMZwzFe5c6ff" +
                "HuhAkhE8OEzyEZqUlVjXkj1/Rdm2vXWnvmx98J+Gs93OXQep4Qm/McVVvc/vqyASp+2h/qB4WAk3gUJC/35GCDLRDwsmjwkYgjkY" +
                "hWkYiJkYi8kY7rnbb0iQEVQ4DPlQTzHu+9f5DOW3b6rYd3Tyxdstd588f+IL6rWcxatTW1+LnlDZtx0iSYkGLsZthFBTZ8K9gcG0" +
                "mTwmYAjmYBSmYSBmYqzn3nHNVDLwZAQbDk0+tEsQTwhJzIivbsqcs2jCezuq/3Ha1f1gys3vaj89V9rxsYLItNdjy2q9ljMqiMSN" +
                "EHVqgC1OBwsmyVSZMNNm8piAIZiDUZiGgZjped4kxlcKlYAxcGQMABz9+JBIMZ6FblYRdXv2/JUlW3f3vBzmUfONx7XHPi/bvp/I" +
                "nP7q3IRqV9/7LfUoiQs6EN5MuN/6yPSYJFNlwso7d248xgQMwRyMwjTP04uqWBimkshg+24A4BDhQzOE/DYsNjLfmdIyY/yiVRTz" +
                "CiJfPXTfFDJx9yFqunFzl6ZMeSWmtKb3/dpCoEgRo9uD34hMg8kwJSbG9Jik+1YMps3kMQFDMEd5Fr53R1wzYAwuGQMGh3CK0UBk" +
                "RERiVFHFmKkzxy9sL9nyETF58pd3qOYaL9yq+vtJVoN5KzZkzl6Q3DQdxygb8O7vf5EDRbip9BzPoAzNBJgGk2FKTIzpMUmmyoSZ" +
                "NpPHBAzxvD9DMGAMaCoZLDj8+RAMIf0QKZiY3PzyuLffLdr4IdVc/ZmrfCin3Pq+/rMrlQeOl2zZnb9yY9bvF1P6EdKj8p1KOHF/" +
                "P6HlbVQCnTMEAzEcgzI0E2AaTIYpKfcknLnKJJkqE2baTF4TC/2AMRhkDDwceinGKIT0JZrR2cUs/DJmvZO3ciPrQD6Xjedvtnzz" +
                "E7VeQ9c1PrLlfz1QtL4jd8mazDkLKQaTGqbGOusic8v4fCv7JapxRb+Fx3Mip9MJXdEh3dI5QzAQwzEoQzMBpsFkmBITY3pMkqkq" +
                "G+FaSUQiYEQOsLMGHg5BPowQ6Xl/ckxZLfk7661lBas3l+84gEteOHd9ytffT733c9PluyT7qoP/dO7sLH5/Z8Gqv7BeoA5InzkP" +
                "v6a4Xkqsb4mvaopz1pMOWGdGF07ik03jB37lj/yLAziMgzmFEzmdTuiKDumWzhmCgRiOQRmaCTANJsOUmBjT87xD2BiLoUbGYMFh" +
                "JSK/DYsblVEQN+mFMcT2uUvz//hn1gIE89rj50n5+Kz14S8sE5QvZj51qebwmYr9x5y7DvKxxsFFG7YVrtlS0L6JjMCaIu/dPylt" +
                "+Xp+5Y/8iwM4jIM5hRM5vef7Fr+mQ7qlc4ZgIIZjUIZmAkyDySjfVdD7RvqnEotBh0OVD1lE+iihVAxPz+PDyhIxfca87AV/4CNO" +
                "Gch6oerQKeX71c/fdHU/ePHOk9ZH/225+6Oy33DtvvsZIeX7yM52kxeUdrabX91PYXGAkinu/sgpnMjpdEJXdEi3dM4QDMRwDMrQ" +
                "TMBzv5YGEyJYDA0yBh0O4xAijEi/WNLz/ZWkeaU4aJyWNv2NzDmLWEDmt2+asHE7i0nnrk4+6ySFmsNdfO5xdv3pyxSPbjj4gV/5" +
                "I//iAA7jYE7hRE6nE7qiQ7qlc4ZgIM93L+oyYYBF1JDCYujA4c2HICJilLjXOCwrInJKKCPia1x8xMe0zhr76tyM2QvIAtnzV7DC" +
                "zFmyJnfZ2txl63raWn7lj/yLAziMgzmFEzmdTuhKWQT1rTsEmZDCInIo+GWIwCGUZbwRMQwkKqD8ut4ZGZ0SmpgRnppDccBHPyKn" +
                "NDKvPDLfqbS8cn7lj/yLAziMg/utNcSAUAsVmliEDDkshiAcooioU2IMijYuok2g/xARJoY6FkMWDh1E9AOJLCWWNjUm9ELF0MZi" +
                "iMPhV4hIBBJvUEKCTUO0/+jCoWLokjHE4dAvV9Up0QDFmxUpaFRPVBviN/pMhDw1TDxdcBgGkkgNx2iBIsCNBgFiQOgzEfm0aP4U" +
                "waGBiBgl8sSIcyDOROTTpfZTB4c4JaKsBNb8Rnz6mRgGcOhSog5K4Lho9PncsGJiOMFhRIkxLpLNcKDhIulwgkMGFOvbMJRxuMIR" +
                "bFyeCdGeHThk0bE1seGwmw2H3Ww47GZl+39CFCr5/LkHGgAAAABJRU5ErkJggg==");
            ContentTypes["/favicon.ico"] = "image/png";

        }
    }
}
